/**
 * legado 书源格式语义覆盖矩阵（数据表）——「彻底兼容 legado」这条目标的**唯一读数口**。
 *
 * 规格来源：legado 3.26 参考实现的代码级盘点（会话产出，不入库）。本表把那份清单的每一条
 * 能力落成一行，每行必须归入三态之一：
 *   implemented    本仓已实现——`impl` 指向实现它的源码符号，`test` 指向钉住它的测试标题片段
 *   not-applicable 环境不适用或对面即 dead——`doc` 指向 `docs/design/*.md` 里写明这条口径的锚点
 *   open           已知欠账 / 待拍板——`note` 讲清缺什么、卡在谁手上
 *
 * 为什么做成机器守卫而不是文档：这些判据会被改名、被删、被写歪。`coverage.test.ts` 逐行验
 * 「文件在不在、符号/锚点在不在」，任一条漂移即红——比人肉维护的清单可靠，也比「注释说已支持」诚实。
 *
 * 刻意不设「未知」态：一行的归属只能是上面三态之一，写不出来就编译不过。
 */

export type CoverageStatus = 'implemented' | 'not-applicable' | 'open'

export type CoverageGroup =
  | 'A 规则语法' | 'B URL 与请求' | 'C 书源字段' | 'D 搜索与发现' | 'E 书籍详情'
  | 'F 目录' | 'G 正文' | 'H JS 宿主面' | 'I App 级规则族' | 'J 评论与源类型' | 'K 书源管理与调试'

export interface CoverageRow {
  /** 稳定 id：改名即断言失败，防止同一能力被抄成两行 */
  id: string
  group: CoverageGroup
  /** legado 侧的能力名（尽量用对面的符号/字段名，便于回查） */
  capability: string
  status: CoverageStatus
  /** [源码文件, 必须出现在该文件里的符号或原文] */
  impl?: [string, string]
  /** [测试文件, 必须出现在该文件里的用例标题片段] */
  test?: [string, string]
  /** [文档文件, 必须出现在该文档里的锚点措辞]（not-applicable 必填）。
   *  锚点必须是 `docs/design/legado-compat.md`「环境不适用的面」表里的 `不适用：…` 条目：
   *  裁决只在那张表里写一遍、行拿锚点回指（两处各写一份理由会立刻长出两份抄本）；
   *  反向也由守卫把住——表里每条裁决都要有行认领，否则等于把裁决写成遗忘。 */
  doc?: [string, string]
  note?: string
}

export const COVERAGE: CoverageRow[] = [
  // ── A 规则语法 ──────────────────────────────────────────────────────
  { id: 'a-combining-or', group: 'A 规则语法', capability: '|| 熔断回退（空 List 继续向右）', status: 'implemented', impl: ['src/engine/combine.ts', 'combineFirst'], test: ['tests/engine/combine.test.ts', '空 list，不折叠成 miss'] },
  { id: 'a-combining-and', group: 'A 规则语法', capability: '&& 串联合并（并集语义）', status: 'implemented', impl: ['src/engine/combine.ts', 'combineAnd'], test: ['tests/engine/combine.test.ts', '&&'] },
  { id: 'a-combining-zip', group: 'A 规则语法', capability: '%% 交叉合并（按下标交替）', status: 'implemented', impl: ['src/engine/combine.ts', 'combineZip'], test: ['tests/engine/combine.test.ts', '%%'] },
  { id: 'a-combining-mixed', group: 'A 规则语法', capability: '同链混用连接符', status: 'implemented', impl: ['src/engine/parse.ts', '一条规则混用了多个连接符'], note: 'legado 允许混用（elementsType 取实际生效者）；本仓判为语义冲突、解析期炸——刻意分歧，见 engine.md', test: ['tests/engine/parse.test.ts', '混用'] },
  { id: 'a-reverse-prefix', group: 'A 规则语法', capability: '链首 `-` 反序', status: 'implemented', impl: ['src/engine/parse.ts', 'reverse'], test: ['tests/engine/combine.test.ts', '反序'] },
  { id: 'a-plus-prefix', group: 'A 规则语法', capability: '列表规则 `+` 前缀（历史 all-in-one 标记，legado 只剥不做事）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：列表规则 + 前缀'], note: '对面剥掉即等价于不识别；本仓按未知段处理会在解析期炸——真机库零出现（本机 158 源扫描）' },
  { id: 'a-allinone', group: 'A 规则语法', capability: '`:regex` AllInOne 整页正则（二维 matches）', status: 'implemented', impl: ['src/engine/allinone.ts', 'evalAllInOne'], test: ['tests/engine/allinone.test.ts', '二维'] },
  { id: 'a-allinone-inline-flags', group: 'A 规则语法', capability: 'Java 行内标志 (?s)/(?i)', status: 'implemented', impl: ['src/engine/allinone.ts', 'INLINE_FLAG_RE'], test: ['tests/engine/content-facet.test.ts', '行内标志'] },
  { id: 'a-allinone-chain-position', group: 'A 规则语法', capability: 'AllInOne 只可在分支首位', status: 'implemented', impl: ['src/engine/evaluate.ts', 'AllInOne 段必须是分支首位'], test: ['tests/engine/parse.test.ts', 'css / jsonpath / AllInOne 识别'] },
  { id: 'a-replace-tail', group: 'A 规则语法', capability: '`##pattern##replacement` 净化尾（全量）', status: 'implemented', impl: ['src/engine/replace.ts', 'applyReplaces'], test: ['tests/engine/replace.test.ts', '循环替换'] },
  { id: 'a-replace-only-one', group: 'A 规则语法', capability: '`###` OnlyOne（只替第一个匹配）', status: 'implemented', impl: ['src/engine/grammar.ts', 'onlyOne'], test: ['tests/engine/replace.test.ts', 'OnlyOne'] },
  { id: 'a-replace-group-refs', group: 'A 规则语法', capability: '替换串 `$1` 分组引用', status: 'implemented', impl: ['src/engine/replace.ts', 'applyReplaces'], test: ['tests/engine/replace.test.ts', '$1'] },
  { id: 'a-replace-empty-rule', group: 'A 规则语法', capability: '空规则纯替换（`##a##b` 无链体）', status: 'implemented', impl: ['src/engine/parse.ts', "rest === ''"], test: ['tests/engine/trace.test.ts', '独立净化形态'] },
  { id: 'a-replace-interp', group: 'A 规则语法', capability: '替换 pattern/replacement 内 `{{book.x}}` 插值（legado makeUpRule）', status: 'implemented', impl: ['src/engine/replace.ts', 'applyReplaces'], test: ['tests/engine/content-facet.test.ts', '## 替换尾 {{chapter.title}} 插值'] },
  { id: 'a-default-selectors', group: 'A 规则语法', capability: 'default 方言 children/class/tag/id/text 选择段', status: 'implemented', impl: ['src/engine/select.ts', 'evalDefault'], test: ['tests/engine/select.test.ts', 'class / tag / id / child'] },
  { id: 'a-text-containing', group: 'A 规则语法', capability: '`text.<串>` 按文本选元素（getElementsContainingOwnText）', status: 'implemented', impl: ['src/engine/select.ts', 'textContaining'], test: ['tests/engine/content-facet.test.ts', '按文本选元素'] },
  { id: 'a-get-terminals', group: 'A 规则语法', capability: '取值终端 text/textAll/ownText/textNodes/html/all/href/src/content', status: 'implemented', impl: ['src/engine/select.ts', 'GET_MODES'], test: ['tests/engine/select.test.ts', 'ownText'] },
  { id: 'a-attr-terminal', group: 'A 规则语法', capability: '取值用途链尾未知词 = HTML 属性名（含向下兜底）', status: 'implemented', impl: ['src/engine/select.ts', 'attrFallback'], test: ['tests/engine/content-facet.test.ts', '属性终端'] },
  { id: 'a-rule-usage-axis', group: 'A 规则语法', capability: 'getString / getElements 两种用途分叉', status: 'implemented', impl: ['src/engine/types.ts', 'RuleUsage'], test: ['tests/services/probe.test.ts', 'usage'] },
  { id: 'a-index-suffix', group: 'A 规则语法', capability: '点号位置后缀 `.all`/`.N`/`.a:b`（半开）', status: 'implemented', impl: ['src/engine/select.ts', 'applyIndex'], test: ['tests/engine/select.test.ts', '位置索引：正/负/越界'] },
  { id: 'a-bracket-single', group: 'A 规则语法', capability: '方括号 `[n]` / `[a:b[:c]]` 闭区间、负数、`[-1:0]` 倒序', status: 'implemented', impl: ['src/engine/select.ts', 'positionsFor'], test: ['tests/engine/content-facet.test.ts', '方括号索引'] },
  { id: 'a-bracket-multi', group: 'A 规则语法', capability: '方括号多条目并集 `[a,b,…]`（去重、越界丢弃、文档序）', status: 'implemented', impl: ['src/engine/types.ts', "'multi'"], test: ['tests/engine/content-facet.test.ts', '方括号多条目'] },
  { id: 'a-exclude', group: 'A 规则语法', capability: '`!` 排除语法（`!0:2:-1`、`[!0]`）', status: 'implemented', impl: ['src/engine/select.ts', 'applyExclude'], test: ['tests/engine/reduce.test.ts', '排除'] },
  { id: 'a-index-vs-exclude', group: 'A 规则语法', capability: '位置索引与 `!` 排除并存', status: 'implemented', impl: ['src/engine/parse.ts', '位置索引与 ! 排除语法不并存'], note: 'legado 亦二选一；本仓在解析期点名抛错', test: ['tests/engine/parse.test.ts', '位置索引与 ! 排除并存 → 解析期抛错'] },
  { id: 'a-css-explicit', group: 'A 规则语法', capability: '`@css:` 强制 CSS（含 `!` 排除）', status: 'implemented', impl: ['src/engine/css.ts', 'evalCss'], test: ['tests/engine/css.test.ts', 'find'] },
  { id: 'a-css-implicit', group: 'A 规则语法', capability: '未知词隐式回落 CSS（含选择器特征字符）', status: 'implemented', impl: ['src/engine/parse.ts', 'isImplicitCss'], test: ['tests/engine/parse.test.ts', '选择器特征字符'] },
  { id: 'a-xpath-subset', group: 'A 规则语法', capability: 'XPath 子集（元素/text()/@attr，轴 child/parent(..)/following/preceding-sibling，函数 contains/starts-with/not/position/last）', status: 'implemented', impl: ['src/engine/xpath.ts', 'evalXPath'], test: ['tests/engine/xpath.test.ts', '谓词按父分组'] },
  { id: 'a-xpath-path-exists-predicate', group: 'A 规则语法', capability: '谓词内的相对路径存在性（li[.//a]、[a/@href]：节点集非空即真）', status: 'implemented', impl: ['src/engine/xpath.ts', 'pathHits'], test: ['tests/engine/xpath.test.ts', '相对路径存在性谓词'], note: '对面 JsoupXpath 按 XPath 1.0 节点集谓词判存在；本仓此前谓词白名单只有裸元素名，.// 起步直接抛「谓词无法识别」。属性步按属性节点存在性过滤（属性不在子节点链上），谓词内 // 起步仍如实抛——那是文档根绝对轴，本求值器只有上下文节点，不猜成后代。真机实证 1 源（搬山人小说网 ruleChapterList，卷内「有链接的 li」才是章节行）' },
  { id: 'a-no-tail-js-split', group: 'A 规则语法', capability: "链尾 (…) **不是** js 表达式形态（对面从不切它）", status: 'implemented', impl: ['src/engine/parse.ts', 'classifySegment'], test: ['tests/engine/parse.test.ts', '链尾 (…) 不是 js 形态'], note: "对面证据两条：SourceRule.init 只在 @js: / <js> / @XPath: / @Json: 与前缀斜杠上定模式（整条 /text() 进 XPath）；RuleAnalyzer.splitRule 用 findToAny 配 chompBalanced **跳过**平衡组，不在左括号处切。本仓曾有 detectTailJs 把末元素的 (…) 当 js 表达式——真机实证它把耽美小说 ruleToc.chapterName 的 /text() 切成 /text 与 () 两段（空括号当脚本编译当场 Unexpected token），而全库 158 源需要这条形态的为 0（普查 12 条以右括号结尾的候选全是 ## 正则尾与 has/not 伪类）。已移除，连 Segment.form 的 tail 分支与 evaluate 的 return 包装一起；Default 链末段的 text(…) 写法随之落进与 text下一页 同族的「认不出末段」待拍板口径" },
  { id: 'a-xpath-parent-step', group: 'A 规则语法', capability: 'XPath 父步 `..`（含连续父步、攀过文档根、父步上挂谓词与属性末段）', status: 'implemented', impl: ['src/engine/xpath.ts', "if (body === '..')"], test: ['tests/engine/xpath.test.ts', '三级父步后接逆向兄弟轴'], note: '本机库步骤普查分母：144 条 XPath 段 / 12 源，白名单外真实形态只有父步 2 源 4 条规则（正文 `//a[text()="下一页"]/../../../preceding-sibling::div[1]`、目录 `//a[text()="下一页"]/../following-sibling::li/a`）。属性通配 `@*`、自身步 `.`、ancestor 轴实测零需求 → 仍解析期抛错' },
  { id: 'a-xpath-other-axes', group: 'A 规则语法', capability: '其余轴（ancestor/descendant-or-self/namespace）与 count/sum 等函数', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：XPath 子集外的轴与函数'], note: '274 条真实规则实测出的子集边界；越界一律解析期抛错而非猜' },
  { id: 'a-json-path-subset', group: 'A 规则语法', capability: 'JSONPath 子集（$/.name/..name/[n]/[a:b]/[*]/.*/.[*]，负数从尾数）', status: 'implemented', impl: ['src/engine/jsonpath.ts', 'evalJsonPath'], test: ['tests/engine/jsonpath.test.ts', '负数从尾数'] },
  { id: 'a-json-path-filter', group: 'A 规则语法', capability: 'JSONPath 过滤器 `[?(…)]` / 脚本表达式 `[(…)]`', status: 'open', note: '本机库零需求。**2026-09-22 由解析面普查证实**（`tests/engine/parse-census.test.ts` 把现库每条规则串真过 `parseRule`，4170 条里没有一条因过滤器/脚本表达式被拒）——早先用正则数出「24 源带该形态」是假的，命中的是 js 里的 `new RegExp(\x27[?&]\x27…)` 字面量，教训已写进 AGENTS.md 现量口径。『彻底兼容』口径下仍需实现或改判环境不适用，但排到队尾' },
  { id: 'a-json-path-inline', group: 'A 规则语法', capability: '`{$.path}` 单括号内嵌（JSONPath 侧）', status: 'implemented', impl: ['src/engine/literal.ts', 'splitLiteral'], test: ['tests/engine/tocurl-interpolation.test.ts', '单花括号内嵌形态'] },
  { id: 'a-json-context-terminal', group: 'A 规则语法', capability: '内容是 JSON 对象时，裸词终端（`url`/`name`/`href`/`src`）按属性读而非 DOM 属性', status: 'implemented', impl: ['src/engine/evaluate.ts', 'jsonObjectOf'], test: ['tests/engine/content-facet.test.ts', '链尾裸词 → 读 JSON 属性'], note: '对面按内容类型分派：`isJSON` 时整条规则走 AnalyzeByJSonPath（`model/analyzeRule/AnalyzeRule.kt`）。真机实证：麻豆传媒AI / 中文书城 / 全本小说型 `ruleChapterUrl: url`——此前恒 0 命中 → 逐章回退目录页 → 「未取到任何章节地址」。HTML 条目一律不抢（`img@_src` 与 `<a href>` 两条钉子守着）' },
  { id: 'a-json-context-selector-modes', group: 'A 规则语法', capability: 'JSON 条目上裸词 `id`/`class`/`tag` 的属性读（对面 isJSON 分支同样走 JSONPath）', status: 'open', note: '本仓这三个裸词是**选择段**（`id` → 按 id 选元素），所以 JSON 条目里名为 `id` 的字段读不出来（须写 `$.id`）。对面在 isJSON 下根本不碰 DOM，会读成属性。**2026-09-22 现量 0/158**：全库条目级规则里以裸词 `id`/`class`/`tag` 收尾的为 0（正则按「末段是这三个裸词且不是 `@词` 终端」筛）。闸已经有了（`evaluate.jsonObjectOf` 只在当前内容本身是 JSON 对象时才改走 JSONPath，HTML 片段与数组不进这条），真要接是一行判定；但没有任何源用它，且改了会影响**非 JSON** 内容的读法（那才是风险面）→ 保持开口，出现该形态的源再补' },
  { id: 'a-make-up-rule-in-js', group: 'A 规则语法', capability: "js 段代码文本里的 {{…}} 也先由 makeUpRule 插值再执行", status: 'implemented', impl: ['src/engine/evaluate.ts', 'interpolateTemplate'], test: ['tests/engine/js-template.test.ts', 'JSONPath 内嵌段被替换进字符串字面量'], note: "对面段循环顺序是 putRule → makeUpRule(result) → 按 mode 分发（model/analyzeRule/AnalyzeRule.kt getString 段循环），makeUpRule 重写的是**规则文本本身**，故 js 段里的字符串字面量同样被替换——真实源大量靠它拼 URL（米读小说 ruleBookInfo.tocUrl 与 ruleToc.chapterUrl 的 chapter_list 形态）。全库 158 源里 28 源在 js 段嵌 {{…}}。本仓此前只对模板字面段插值，js 段原样进沙箱 → 返回带字面花括号的残 URL 直接发上网（真机实证：米读小说 toc 404 打到 chapter_list/100/ 加字面花括号加 .txt）。现与字面段共用 interpolateTemplate 单点：插值段 Miss → 整段 Miss，不发残 URL。**js 文本只认双花括号**（splitLiteral 的 doubleBraceOnly 口径）：单括号 {$…} 在脚本里通常是 JS 模板字面量 ${expr} 的一部分，按内嵌 JSONPath 撕走会让中文书城 ruleToc.chapterList 整段 Miss、目录 0 章（第 14 批真机回退、第 15 批前修掉，回归钉在 js-template.test.ts）" },
  { id: 'a-template-braces', group: 'A 规则语法', capability: '`{{expr}}`：子规则 vs JS 二判（@ / $. / $[ / // 前缀算规则）+ 多值逆序还原', status: 'implemented', impl: ['src/engine/literal.ts', 'classifyExpr'], test: ['tests/engine/content-facet.test.ts', '模板字面段'] },
  { id: 'a-template-escaped-at', group: 'A 规则语法', capability: '`@@<rule>` 转义强制按 Default 处理', status: 'implemented', impl: ['src/engine/parse.ts', 'splitElements'], test: ['tests/engine/parse.test.ts', '@@ 段内剥一个 @ 后按常规识别'] },
  { id: 'a-get-brace-form', group: 'A 规则语法', capability: '`@get:{name}` 花括号形态', status: 'implemented', impl: ['src/engine/parse.ts', "startsWith('get:')"], test: ['tests/engine/parse.test.ts', 'put / getvar 识别'] },
  { id: 'a-put-region', group: 'A 规则语法', capability: '`@put:{…}` 在任何切分前剥离（体内 @ 非段界）', status: 'implemented', impl: ['src/engine/grammar.ts', 'putRegionEnd'], test: ['tests/engine/parse.test.ts', 'put / getvar 识别'] },
  { id: 'a-brace-region-atomic', group: 'A 规则语法', capability: '`{{…}}` 花括号区在任何 @ 切分前整体剥出（区内 `@@规则` 不是段界）', status: 'implemented', impl: ['src/engine/grammar.ts', 'braceRegion'], test: ['tests/engine/content-facet.test.ts', '区内规则递归求值'] , note: '对面 makeUpRule 先于 splitRule 完成插值；本仓过去只在字面段认括号，链切分不认 → 4 源 intro 解析期炸。引号感知 + 嵌套深度' },
  { id: 'a-brace-region-combinator', group: 'A 规则语法', capability: '`{{…}}` 区内的 `||`/`&&`/`%%` 不算连接符（插值先于组合切分）', status: 'implemented', impl: ['src/engine/parse.ts', 'splitTop'], test: ['tests/engine/parse.test.ts', '内的 `&&` 同样不切'], note: '真源实证两条：英文小说 ruleContent 的 `{{@css:.a@text||.b@text}}`、米读小说 intro 的 `{{(function(){…&&…})()}}`（4.9KB 规则）。对面靠"先插值再切分"达成同一结果' },
  { id: 'a-blank-branch-dropped', group: 'A 规则语法', capability: '连接符切出的空白分支被丢弃（`A&&&&B`、尾随 `&&`、纯空白换行）', status: 'implemented', impl: ['src/engine/parse.ts', 'parseBranch'], test: ['tests/engine/parse.test.ts', '空白分支**被丢弃'], note: '对面 `RuleAnalyzer.splitRule` 不滤空串，但空规则取值是 `getElements("")` → 空列表，`&&`/`||`/`%%` 合并时自然不贡献——等价于丢分支。本仓此前在 parseBranch 抛「空分支」，等于把对面读得出的规则整条判死；现与 `rest === \'\'` 同路（零分支即空，不静默产假值）。真源实证：某源 `ruleBookInfo.kind` 的多行 `&&&&` 形态（解析面普查第 22 批抓到）' },
  { id: 'a-blank-segment-dropped', group: 'A 规则语法', capability: '空白段不成段（`</js>` 与 ## 尾之间的换行、边界残留空串）', status: 'implemented', impl: ['src/engine/parse.ts', 'splitElements'], test: ['tests/engine/parse.test.ts', '孤立换行不成段'], note: '对面 RuleAnalyzer.trim 跳过 `<\'!\'` 字符 + 列表切分 filterNot isBlank；世界名著网 ruleBookUrl 实证' },
  { id: 'a-put-value-getString', group: 'A 规则语法', capability: '@put 值按 getString 求值（任意规则形态、多值 \\n 拼接）', status: 'implemented', impl: ['src/engine/variables.ts', 'isRuleFormValue'], test: ['tests/engine/variables.test.ts', '值为规则串'] },
  { id: 'a-put-only-rule', group: 'A 规则语法', capability: '纯 @put 规则 = 只设变量、不产出新根', status: 'implemented', impl: ['src/engine/parse.ts', 'isPutOnlyRule'], test: ['tests/services/reading.test.ts', '只设变量、不换根'] },
  { id: 'a-put-big-variable', group: 'A 规则语法', capability: '10000 字符大变量分流（落库 vs 内存）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：变量不落盘与大小分流'], note: '对面分流是因为变量要写进 Book 表；本仓 vars 不落盘，无对应问题' },
  { id: 'a-var-scope-chain', group: 'A 规则语法', capability: '变量四级作用域链 chapter→book→ruleData→source', status: 'open', note: '对面 `AnalyzeRule.get` 依序找四级、每级 `.takeIf { it.isNotEmpty() }`（**空串继续下找**），`put` = 第一个存在的宿主。本仓已接两级（`vars`=本次调用的 ruleData/chapter 层 + source 层只读访问器，见 `a-var-source-tier`）；**还缺 chapter/book 两个持久化层**：对面 `Book.variable`/`Chapter.variable` 落库，所以「目录面 @put、正文面读」这类跨门面调用能命中，本仓 \`ctx.vars\` 一次调用一份 ⇒ 那一型仍会 Miss。补它要在服务层给书/章建变量表（含缓存代际与删除清理），属持久化设计不是引擎改一行' },
  { id: 'a-var-source-tier', group: 'A 规则语法', capability: '变量读链的 source 层兜底（java.get / @get: 跨调用可见）', status: 'implemented', impl: ['src/engine/variables.ts', 'getScopedVar'], test: ['tests/engine/js-sandbox.test.ts', 'source.put 写进去的变量'], note: 'source 层与 `source.get/put`、`getVariable` 同一张按源隔离的表（对面 `BookSource.variable`）。取用**只读访问器**而非建档 Map：`session.sourceVars()` 一调就建表，会改掉 `source.getVariable`「从未设置」的语义（本仓有钉子钉着，第一版这样接当场报红）；惰性取值顺带覆盖「同一次调用里先 `source.put` 再 `java.get`」。写仍只写 `ctx.vars`——对面 `put` 是第一个存在的宿主，本仓 `vars` 恒在 ⇒ 同形' },
  { id: 'a-get-bookname-title', group: 'A 规则语法', capability: '内建伪变量 java.get("bookName") / get("title")', status: 'implemented', impl: ['src/engine/variables.ts', 'getRuleVar'], test: ['tests/engine/variables.test.ts', '内建伪变量'], note: '对面 `AnalyzeRule.get` 在四级读链**之前**有两个 when 特例：bookName→book.name、title→chapter.title，且只在对应宿主存在时生效（`book?.let`/`chapter?.let`）。宿主缺席不猜：搜索面没有 book ⇒ 落回读链。与读链同源一个函数，防止两处口径分叉' },
  { id: 'a-js-inline-forms', group: 'A 规则语法', capability: '`@js:`（吃到链尾）与 `<js>…</js>`（任意位置、块后直接续段）', status: 'implemented', impl: ['src/engine/grammar.ts', 'jsRegionEnd'], test: ['tests/engine/parse.test.ts', '吞链尾'] },
  { id: 'a-js-script-form', group: 'A 规则语法', capability: 'js 段「最后一个表达式即结果」（Rhino 脚本形态）', status: 'implemented', impl: ['src/engine/evaluate.ts', 'scriptForm'], test: ['tests/engine/run-script.test.ts', '完成值即结果'] },
  { id: 'a-mode-flip-on-template', group: 'A 规则语法', capability: '首个 ## 之前出现 {{}}/@get: → 整段翻转为正则/模板', status: 'implemented', impl: ['src/engine/parse.ts', 'braceRegion'], test: ['tests/engine/content-facet.test.ts', '整段翻转为 Regex'] , note: '可观测口径已钉：模板/变量段先展开、展开结果直接进 ## 替换，不回头从页面取根。$n 翻转一条本机库零需求（16 处 $n 全在 JS 代码内）' },
  { id: 'a-mode-webjs-prefix', group: 'A 规则语法', capability: '`@webjs:` 段（Android WebView 执行）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：Android 与 App 宿主能力'], note: '无头环境无 WebView；对面也只在 URL 带 webView:true 时才走' },
  { id: 'a-reduction-contract', group: 'A 规则语法', capability: '取值规约：取位失败→Miss、解析到空集合→空 List，两值永不折叠', status: 'implemented', impl: ['src/engine/select.ts', 'reducePicked'], test: ['tests/engine/reduce.test.ts', '空态裁决'] },
  { id: 'a-segment-loc', group: 'A 规则语法', capability: '段级错误定位（facet + 全规则连续段号 + 段原文）', status: 'implemented', impl: ['src/engine/errors.ts', 'UnsupportedRuleError'], test: ['tests/engine/trace.test.ts', '段级错误定位'] },
  { id: 'a-unknown-segment-throws', group: 'A 规则语法', capability: '认不出的语法解析期抛错（宁炸不猜）', status: 'implemented', impl: ['src/engine/parse.ts', '无法识别的段类型'], test: ['tests/engine/parse.test.ts', '不认识的段抛错且带段索引与原文'], note: '**边界按对面坐实过一次**（2026-09-22）：`ElementsSingle.getElementsSingle` 的 else 分支是 `temp.select(beforeRule)`——白名单外的 `词.词`、非 ASCII tag 在对面的无名不是"认不出"，而是 CSS 选择器。所以「认不出」只剩**构不成选择器语法**的形态（含 `$`、空格等非法字符），那才是本行抛的对象；被否决的替代方案「裸词透传留到求值期」依然成立：构成选择器的在解析期就定性成 css 段，不留到 eval 才炸' },
  { id: 'a-bare-index-segment', group: 'A 规则语法', capability: '无 `@` 单段在取值用途下等于 `attr(整串)`（`kind: "0"` 这类）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：无 @ 单索引段（对面取空）'], note: '对面取值路径（`getStringList`→`getResultList`）按 `@` 切完只剩一段时不做选择，直接 `attr(整串)` → 空；本仓解析期抛「无法识别的段类型」——同一族刻意严格，对面也没读出一句话。**曾经记错过一次**：把 `getElementsSingle`（列表路径的 children 索引）当成通用路径，于是当欠账接了一版 children+索引，实测值荒谬后撤回（现库列表位含 children/纯索引者 0 条）。后果侧已收口：对面包 try/catch 的那五个辅助字段（`e-aux-field-error-isolation`）吞掉该抛错，所以这类源两边都是「该字段为空、书目照收」' },
  { id: 'a-xpath-bare-at-terminal', group: 'A 规则语法', capability: 'XPath 主导链的裸 `@终端`（`//div[1]@html`、`//a@js:`）切成下一级规则', status: 'implemented', impl: ['src/engine/parse.ts', 'xpathPending'], test: ['tests/engine/content-facet.test.ts', '取到前序 div 的 html'], note: '对面 splitRule 先 chompBalanced 拉出 `[...]`/`(...)` 再在 @ 处切；本仓此前把 `//` 头的整链吞进 path（谓词 `[@id]` 与斜杠属性步 `/@href` 留在 path 里是刻意保留——求值层已有属性提取，切了反而多一段）。真机实证：腐小说 ruleContent' },
  { id: 'a-value-terminal-stringify', group: 'A 规则语法', capability: '取值用途（getString 路径）链尾剩节点集 → 逐元素 outerHTML 换行拼接，不抛错', status: 'implemented', impl: ['src/engine/evaluate.ts', 'nodesAsString'], test: ['tests/engine/value-terminal.test.ts', 'XPath 段收尾且只命中一个元素'], note: '对面 getString 走完段循环只无条件转字符串（XPath 模式在段内就按换行 join 命中节点，`##` 尾替换作用于已串化的结果——本仓同序：串化发生在 applyReplaces 之前）。本仓此前在服务层 firstValue 抛「结果不是取值而是节点集」（该抛错**零测试**，只有设计文档记着），把「选了元素忘写 /text()」的合法规则记成引擎侧失败。真机实证 2 源：爱丽丝书屋、搬山人小说网的 ruleSearch.intro。列表用途（ruleBookList/ruleChapterList）不变，仍以节点集交逐条目求值' },
  { id: 'a-xpath-prefix-vs-url-template', group: 'A 规则语法', capability: 'URL 模板优先于 XPath 前缀判定（`/…{{…}}`、`/…{$.x}` 不被当 XPath 截走）', status: 'implemented', impl: ['src/engine/parse.ts', 'interpolated'], test: ['tests/engine/tocurl-interpolation.test.ts', '单花括号内嵌形态'], note: '`{$.rule}` 是对面内嵌 JSONPath（AnalyzeByJSonPath.innerRule），与 `{{}}` 同属插值；真机实证 顶点小说 ruleTocUrl、悦读小说 ruleBookUrl' },
  { id: 'a-xpath-single-slash-prefix', group: 'A 规则语法', capability: "单斜杠开头的顶层规则按 XPath 处理（对面 SourceRule.init 同判据），插值内表达式仍只认 //", status: 'implemented', impl: ["src/engine/parse.ts", "XPATH_HEAD"], test: ["tests/engine/parse.test.ts", "单斜杠开头仍是 XPath"], note: "本行原先写成「本仓额外接受单 /，是对面的扩展」——**判据引错了地方**：SourceRule.init（model/analyzeRule/AnalyzeRule.kt）顶层就是 `startsWith(\"/\")` → Mode.XPath；只认 `//` 的是 SourceRule.isRule（同文件 `private fun isRule`），管的是 {{…}} 内表达式的规则/JS 二分，本仓 classifyExpr 与之逐字对齐。现库量：./ 或 .// 开头的顶层规则 0 源（本仓额外接受 .// 属更宽一侧，无源依赖，如实记）；以单斜杠开头的规则串 84 条全是 URL 形态，由 {{…}} 与选项后缀两条豁免先行接走（顶点小说 tocUrl 实证）。" },
  { id: 'a-lazy-branch-parse', group: 'A 规则语法', capability: '`||` 分支惰性求值：坏分支不拖垮同链的好分支', status: 'open', note: '对面按序试分支，命中即返回——`option@value||text下一页@href`（乐文小说 nextTocUrl）里坏掉的第二支从不影响第一支。**2026-09-22 边界重划后本行只剩原则、没有实证案例**：`text下一页` 根本不是"认不出"（对面 `ElementsSingle` else 分支 = `select(beforeRule)`，本仓现已按 CSS 定性），所以那条源在普查里已经解析通过、不再需要为本行放宽「宁炸不猜」——现库真量 **0 条规则**走到"某支含真·未识别语法"这一步（解析面普查：214 源 / 4170 条里被拒的只剩 5 条 3 源，全是裸索引段族 `a-bare-index-segment`，与本行无关）。本行留着是因为该差异在**原则上**仍在：真出现构不成选择器的分支时，本仓仍会连坐炸掉能用的那支；到那时再拍板' },
  { id: 'a-legacy-2x-migration', group: 'A 规则语法', capability: '2.x 旧规则语法迁移（`#re#` → `##re##`、`|`→`||`、`&`→`&&`）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：2.x 旧格式迁移'], note: '对面 `ImportOldData.toNewRule` 为一次性升级工具；本仓导入即最新 3.x 格式，无 2.x 库存' },

  // ── B URL 与请求 ────────────────────────────────────────────────────
  { id: 'b-param-split', group: 'B URL 与请求', capability: ',{json} 选项分界（\\s*,\\s*(?=\\{)，允许逗号两侧空白）', status: 'implemented', impl: ['src/engine/template.ts', 'URL_OPTION_SPLIT'], test: ['tests/services/url-option.test.ts', '切分：严格 JSON 形态'] },
  { id: 'b-split-unconditional', group: 'B URL 与请求', capability: '无条件切分：选项非法也先把 URL 切干净', status: 'implemented', impl: ['src/services/request.ts', 'splitUrlOption'], test: ['tests/services/url-option.test.ts', '选项尾段不是合法 JSON 也切分'] },
  { id: 'b-opt-method', group: 'B URL 与请求', capability: '选项 method（仅 POST/HEAD 生效，其余 GET）', status: 'implemented', impl: ['src/services/request.ts', 'assembleRequest'], test: ['tests/services/request.test.ts', 'POST'] },
  { id: 'b-opt-body', group: 'B URL 与请求', capability: '选项 body（并做 {{}} 插值）+ POST 表单默认 Content-Type', status: 'implemented', impl: ['src/services/request.ts', 'assembleRequest'], test: ['tests/services/request.test.ts', '表单默认 urlencoded'] },
  { id: 'b-opt-charset', group: 'B URL 与请求', capability: '选项 charset 覆盖解码链', status: 'implemented', impl: ['src/services/fetcher.ts', 'decodeBody'], test: ['tests/services/fetcher.test.ts', '解码链'] },
  { id: 'b-opt-headers', group: 'B URL 与请求', capability: '选项 headers（对象 / 双重编码字符串）', status: 'implemented', impl: ['src/services/request.ts', 'parseHeaders'], test: ['tests/services/request.test.ts', '双重编码'] },
  { id: 'b-opt-webview', group: 'B URL 与请求', capability: '选项 webView:true（走 WebView 渲染）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：Android 与 App 宿主能力'], note: '本插件无头浏览器；对面也只在开 webView 时走。剥掉后缀按普通请求尝试，如实 warning' },
  { id: 'b-opt-unknown-keys', group: 'B URL 与请求', capability: '未实现选项键（retry/type/js/bodyJs/dnsIp/serverID/webJs/origin）', status: 'implemented', impl: ['src/services/request.ts', 'KNOWN_OPTION_KEYS'], test: ['tests/services/request.test.ts', '未知键'], note: '键本身不生效，但当场 warn 点名（宁吵不瞒）；对面 toasts/respondBody/getHttp 等字段本就是 dead' },
  { id: 'b-opt-retry', group: 'B URL 与请求', capability: "选项 retry（仅非 2xx 重试）", status: 'open', note: "键已留痕但不实现。分母订正：2026-09-22 按 raw 现库 214 源里带 retry 字样的是 **0 源**（旧注写「5 源」是在 214/228 源时测的，用户增删后分母漂了——见记忆里「任何分母都现量」）。对面 UrlOption 确有此键且只在非 2xx 时重试，实现点在 fetcher 一处；补与不补都只影响「将来出现这种源」，不影响现库任何一次读取 → 保持开口，不预先造没有需求方的机制" },
  { id: 'b-page-angle-list', group: 'B URL 与请求', capability: '`<a,b,c>` 按页取值（超出取末项 = 到底）', status: 'implemented', impl: ['src/engine/template.ts', 'expandPageAngleList'], test: ['tests/services/request.test.ts', '恩京的书房形态'], note: '对面 AnalyzeUrl 的 pagePattern = Regex("<(.*?)>") + page?.let 段：page < pages.size 取 pages[page-1]、**越界取末项**（= 到底）、选中项 trim 控制符、Kotlin replace 对同一匹配**全量**替换；**page 不参与时整段不动**（本仓同口径：vars.page 非数字即原样）。真源实证：恩京的书房 /<,page/{{page}}/>?s={{key}} —— page=1 首项是空串 ⇒ 对面整段消失，本仓此前原样带尖括号发出去，两边发的 URL 不同（保真差，非坏源；现量 5/214 源）。落点在 assembleRequest 插值之后（与对面 key/js→page→选项切分同位）' },
  { id: 'b-url-js-first', group: 'B URL 与请求', capability: 'URL 的 @js:/<js> 形态先求值（含 key/page/result 绑定）', status: 'implemented', impl: ['src/services/search-template.ts', 'resolveJsSearchTemplate'], test: ['tests/engine/run-script.test.ts', 'key/page/header 经沙箱全局可见'] },
  { id: 'b-url-result-token', group: 'B URL 与请求', capability: "URL 里的 @result 占位（对面在 {{…}} 段算完后整体替换）", status: 'open', note: "对面语义已坐实在 model/analyzeRule/AnalyzeUrl.kt：逐个 {{…}} 段求值后 `result = it.replace(\"@result\", result)`，即把 URL 里剩余的 @result 换成该段结果，最后 ruleUrl = result。本仓 js 侧用 result 全局与 {{result}}，没有这条字面 @result 替换。现库量：**0 源**使用（正则 @result 全库扫描）。对面函数是 `analyzeJs`（原文 `result = it.replace('@result', result)`）；出现该形态的源时按那一条补，不凭空造" },
  { id: 'b-template-vars', group: 'B URL 与请求', capability: '`{{key}}`/`{{page}}` 与 `{{js 表达式}}` 混合插值', status: 'implemented', impl: ['src/engine/template.ts', 'interpolateUrl'], test: ['tests/engine/template.test.ts', '特殊字符做 URI 编码'] },
  { id: 'b-relative-abs', group: 'B URL 与请求', capability: '相对 URL 按 baseUrl 绝对化（javascript:/空 → 不猜）', status: 'implemented', impl: ['src/services/url.ts', 'absUrl'], test: ['tests/services/request.test.ts', 'baseUrl=null 不做绝对化'] },
  { id: 'b-url-option-on-chapter-url', group: 'B URL 与请求', capability: '章节/书籍 URL 保留 `,{option}` 尾巴（每章可带独立请求选项）', status: 'implemented', impl: ['src/services/request.ts', 'absUrlKeepOption'], test: ['tests/services/reading.test.ts', '书 URL 承载请求选项'] },
  { id: 'b-url-option-on-toc-url', group: 'B URL 与请求', capability: 'tocUrl 带 ,{option} 时选项要活到抓取层（绝对化只作用 URL 部分）', status: 'implemented', impl: ['src/services/reading.ts', 'absUrlKeepOption'], test: ['tests/services/toc-url-option.test.ts', '目录请求打到干净端点并带 POST 选项'], note: '对面 BookChapter.getAbsoluteURL 同款口径。absUrl 先跑会让 new URL() 吃掉换行并把花括号百分号编码，,{ 形状一坏抓取层就切不到——真机实证 2 源（悦读小说 / 新小书亭，选项 JSON 分行写）' },
  { id: 'b-canon-url', group: 'B URL 与请求', capability: '比对/防环用归一口径 canonUrl', status: 'implemented', impl: ['src/services/request.ts', 'canonUrl'], test: ['tests/services/url-option.test.ts', 'canonUrl'] },
  { id: 'b-trim-first-page', group: 'B URL 与请求', capability: '首页裁掉 `/{{page}}` 段（Native 分页语义）', status: 'implemented', impl: ['src/services/request.ts', 'trimFirstPage'], test: ['tests/services/request.test.ts', 'trimFirstPage'] },
  { id: 'b-header-static', group: 'B URL 与请求', capability: '源级 header 静态 JSON → 请求头（含 Cookie 段合并）', status: 'implemented', impl: ['src/services/fetcher.ts', 'headerOf'], test: ['tests/services/fetcher.test.ts', 'auth 在后占优'] },
  { id: 'b-header-js', group: 'B URL 与请求', capability: '源级 header 的 @js 形态（每请求现算，失败回退静态）', status: 'implemented', impl: ['src/services/bridge.ts', 'resolveHeaders'], test: ['tests/services/resolve-headers.test.ts', '@js 规则求值 → JSON 头表生效'] },
  { id: 'b-login-url', group: 'B URL 与请求', capability: 'loginUrl 两形态（URL 人工 / JS 取 cookie）', status: 'implemented', impl: ['src/services/reading.ts', 'runLogin'], test: ['tests/api/dispatch-sources.test.ts', 'auth'] },
  { id: 'b-login-check-js', group: 'B URL 与请求', capability: 'loginCheckJs（每次响应后跑脚本，可重发请求）', status: 'open', note: '本机 1 源带值；对面在四个阶段各跑一次。属登录面补全，待拍板' },
  { id: 'b-login-ui', group: 'B URL 与请求', capability: 'loginUi 表单描述（RowUi JSON 数组）', status: 'open', note: '本仓沙箱 getLoginInfoMap 返回空表如实仿真；对面表单渲染属 UI 新面，待拍板' },
  { id: 'b-cookie-jar', group: 'B URL 与请求', capability: 'enabledCookieJar + 真实域匹配 CookieStore', status: 'open', note: '本仓 cookie 只有按源隔离的脚本键值表，不读响应 Set-Cookie。**2026-09-22 甄别**：2026-09-22 按 raw 现量 105/214 源在 raw 里声明 `enabledCookieJar=true`（该字段不落 `rules`，只在 raw），但 158 源全链路审计的失败签名聚类里 **0 条**可归因到 cookie（分桶是 404 / 超时 / 缺规则 / 源脚本 match() 取 null / java.webView），jar 组与非 jar 组的 toc 失败率也没有差出方向 → 不预先造 CookieStore（机制没有需求方）。出现「先要一次访问才给正文」的源时按那条源补。读数与表在 `docs/design/legado-compat.md`「需求量读数」' },
  { id: 'b-concurrent-rate', group: 'B URL 与请求', capability: 'concurrentRate 源级限速（`1000` / `20/60000`）', status: 'open', note: '9 源带值；本仓只有全局 searchParallel=5。与「限流敬畏」直接冲突，优先级高' },
  { id: 'b-proxy-per-source', group: 'B URL 与请求', capability: 'header 里的 `proxy` 伪键（socks5/http 带账号）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：源级代理路由'], note: '本仓代理是进程级配置（config > env > Windows 系统代理），不做源级代理路由' },
  { id: 'b-timeout', group: 'B URL 与请求', capability: '超时与 HTTP 非 2xx 分类（FetchError）', status: 'implemented', impl: ['src/services/fetcher.ts', 'FetchError'], test: ['tests/services/fetcher.test.ts', 'FetchError'] },
  { id: 'b-redirect-landing', group: 'B URL 与请求', capability: '重定向后以落地地址为规则/相对链接基准', status: 'implemented', impl: ['src/services/search-face.ts', 'landedUrl'], test: ['tests/services/search-face.test.ts', 'landedUrl'] },
  { id: 'b-ua-default', group: 'B URL 与请求', capability: '缺省浏览器 UA（对面由全局设置注入 UA）', status: 'implemented', impl: ['src/services/fetcher.ts', 'DEFAULT_HEADERS'], test: ['tests/services/fetcher.test.ts', '缺省带浏览器 UA/Accept 头'] },
  { id: 'b-data-uri-body', group: 'B URL 与请求', capability: 'data:…;base64 URI 直接解字节', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：data: URI 直接解字节'], note: '本机库 0 源使用；本仓二进制通道只有 downloadFile + ctx.fetchRaw' },
  { id: 'b-dns-ip', group: 'B URL 与请求', capability: 'dnsIp / serverID 自定义解析', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：dnsIp / serverID 自定义解析'], note: '属 Android/OkHttp 侧能力，Node undici 无对应；键名已进未知键 warn' },

  // ── C 书源字段 ──────────────────────────────────────────────────────
  { id: 'c-identity', group: 'C 书源字段', capability: 'bookSourceUrl/Name/Group/Comment/customOrder/enabled 身份与启停', status: 'implemented', impl: ['src/services/normalize.ts', 'splitGroups'], test: ['tests/services/normalize.test.ts', '分组拆分'] },
  { id: 'c-book-source-type', group: 'C 书源字段', capability: 'bookSourceType 0/-1 文本、1 音频、2 图片、3 文件、表外 unknown', status: 'implemented', impl: ['src/services/normalize.ts', 'CONTENT_KIND_OF'], test: ['tests/services/normalize.test.ts', '1/2/3'] },
  { id: 'c-header', group: 'C 书源字段', capability: 'header 双形态（JSON / @js 规则）互斥同源', status: 'implemented', impl: ['src/services/normalize.ts', 'normalizeHeaderRule'], test: ['tests/services/normalize.test.ts', 'header JSON 解析失败'] },
  { id: 'c-js-lib', group: 'C 书源字段', capability: 'jsLib（源级全局 JS 库，先于用户代码执行）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'jsLib'], test: ['tests/engine/js-sandbox.test.ts', 'jsLib'] },
  { id: 'c-js-lib-url-dict', group: 'C 书源字段', capability: 'jsLib 的 URL 字典形态（{"名":"https://…"} 下载+按 URL 缓存）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'resolveJsLib'], test: ['tests/engine/js-sandbox.test.ts', 'jsLib 的 URL 字典形态'], note: '1 源在用（crypto-js），且它是 2 个 CryptoJS 源的前置；下载失败与无网络能力都如实抛，不降级成空库' },
  { id: 'c-search-url', group: 'C 书源字段', capability: 'searchUrl → rules.searchUrl', status: 'implemented', impl: ['src/services/normalize.ts', 'RULE_FIELDS'], test: ['tests/services/normalize.test.ts', '驼峰字段全映射'] },
  { id: 'c-explore-url', group: 'C 书源字段', capability: 'exploreUrl + ruleExplore 整块', status: 'open', note: '读入但零消费者。2026-09-22 按 raw 现量 **168/214 源带值**——在册最大的一条缺口。发现面属新增功能（门面 + UI 入口），待拍板' },
  { id: 'c-review-url', group: 'C 书源字段', capability: 'reviewUrl + ruleReview（评论规则）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：评论与段评面'], note: '对面 Converters 把 ruleReview 序列化成 "null"、全仓无读取点（即 dead）；本库 0 源带值' },
  { id: 'c-check-key-word', group: 'C 书源字段', capability: 'ruleSearch.checkKeyWord → 探针关键词', status: 'implemented', impl: ['src/services/normalize.ts', 'probeKeyword'], test: ['tests/services/probe.test.ts', 'checkKeyWord'] },
  { id: 'c-book-url-pattern', group: 'C 书源字段', capability: 'bookUrlPattern（搜索响应即详情页的嗅探）', status: 'implemented', impl: ['src/services/search-face.ts', 'patternOf'], test: ['tests/services/search-book-url-pattern.test.ts', '整串命中'], doc: ['docs/design/services.md', '详情页嗅探'], note: '对面 `String.matches` 是**整串**语义 → 本仓锚定 `^(?:…)$`（2026-09-22 按 raw 现量 41 个带值源里有 `\\/novel\\/[0-9]+\\.html` 这种永不整串等于 URL 的写法，裸 test 会误判成详情页）。详情形态只对声明了 ruleBookInfo.name 的源开放（现库 127/158 声明；27 个带 pattern 的源全在内）——否则一次零结果的搜索会被平铺方言的字段回退展开成假书目' },
  { id: 'c-rule-search-subfields', group: 'C 书源字段', capability: 'ruleSearch 的 kind / wordCount 条目字段（对面共读九项，本仓九项齐）', status: 'implemented', impl: ['src/services/bridge.ts', 'kindFieldOf'], test: ['tests/services/bridge.test.ts', '多命中 → 逗号串'], note: '对面 `bookListRule.` 的全部消费点经全仓 grep 恰为九项：bookList/name/author/bookUrl/coverUrl/intro/kind/lastChapter/wordCount——本仓逐项对上。**`updateTime` 不在列**（`ruleSearch.updateTime` 对面根本不读，只有 `ruleToc.updateTime` 有人消费，见 `c-toc-flags`），此前把三键并列写成本仓欠一项，是照抄字段表没照抄消费点。kind 是 `getStringList().joinToString(",")` 的多值逗号串、wordCount 过 `wordCountFormat`（对面在解析层就格式化，见 `e-word-count-format`）。现量：`ruleSearch.kind` 150 / `wordCount` 42 / `ruleBookInfo.kind` 164 / `wordCount` 55（分母 214 源）。**接入 ≠ 生效**：`rules` 是导入时派生落盘的，所以老库必须有 `SourceRegistry.load` 的 ⑨ 号按 raw 补推迁移，否则该字段对已入库的源恒为 null（审计的「字段到货率」第一轮读出 0/82 源，缺的就是这一步；钉子 `tests/services/sources.test.ts`「存量 rules 缺 kind/wordCount 四键」）' },
  { id: 'c-rule-book-info-init', group: 'C 书源字段', capability: 'ruleBookInfo.init → ruleDetailInit（换根 + 纯 @put 不换根）', status: 'implemented', impl: ['src/services/bridge.ts', 'detailContextOf'], test: ['tests/services/reading.test.ts', 'ruleDetailInit'] },
  { id: 'c-toc-url', group: 'C 书源字段', capability: 'ruleBookInfo.tocUrl（模板插值 + 空则回退 bookUrl）', status: 'implemented', impl: ['src/services/reading.ts', 'tocUrlOf'], test: ['tests/services/reading.test.ts', 'tocUrl 模板'] },
  { id: 'c-can-re-name', group: 'C 书源字段', capability: 'ruleBookInfo.canReName（反直觉真值判定）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：canReName 改名轴'], note: '本仓书架加书即一次快照 + 实时投影，无「改名与否」这条轴；3 源带值无实际影响' },
  { id: 'c-download-urls', group: 'C 书源字段', capability: 'ruleBookInfo.downloadUrls（文件型源）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：仅文本源'], note: 'bookSourceType=3 在入库闸外（本库 2 源带值均为非文本形态）' },
  { id: 'c-related-books', group: 'C 书源字段', capability: 'ruleBookInfo.relatedBooks / homepageModules / customButton / eventListener', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：fork 专属的首页与漫画模块面'], note: 'fork-only 的漫画/首页模块面，不属 legado 通用书源格式' },
  { id: 'c-toc-next', group: 'C 书源字段', capability: 'ruleToc.nextTocUrl / chapterList / chapterName / chapterUrl', status: 'implemented', impl: ['src/services/normalize.ts', 'DIALECT_MAP'], test: ['tests/services/normalize.test.ts', 'ruleToc → ruleChapterList'] },
  { id: 'c-toc-format-js', group: 'C 书源字段', capability: 'ruleToc.formatJs（独立小绑定的章名格式化脚本）', status: 'open', note: '本库非空 0 源（对面绑定 index/chapter/title/gInt 无 java）——矩阵拍板前不投入' },
  { id: 'c-toc-flags', group: 'C 书源字段', capability: 'ruleToc isVolume/isVip/isPay + updateTime 落 tag', status: 'open', note: '11 源带 isVip、4 源 isVolume、17 源 updateTime；本仓 ChapterEntry 只有 {name,url}' },
  { id: 'c-pre-update-js', group: 'C 书源字段', capability: 'ruleToc.preUpdateJs（更新前脚本，含 reGetBook/refreshTocUrl）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：书籍更新检测（preUpdateJs）'], note: '本仓无「书籍更新检测」链路（书架不做版本比对），对面该脚本仅在追更时用；本库 0 源带值' },
  { id: 'c-content-fields', group: 'C 书源字段', capability: 'ruleContent content/nextContentUrl/replaceRegex', status: 'implemented', impl: ['src/services/normalize.ts', 'nextPageUrl'], test: ['tests/services/normalize.test.ts', 'replaceRegex'] },
  { id: 'c-content-title', group: 'C 书源字段', capability: 'ruleContent.title（章名覆盖 + 段评图标 reviewImg）', status: 'open', note: '**2026-09-22 按 raw 现量 10 源**（瀚海书阁 `class.j_chapterName@text`、小说网 `h1@text`、企鹅小说 `class.readTitle@text`、松鹤庭沐·言璃 `$.data.Content[0].ChapterInfo.Title`、耽美小说 `//td/h1/text()`）。对面语义坐实在 `model/webBook/BookContent.kt`（`val titleRule = contentRule.title //先正文再章节名称`）：**拼页之后**跑 title 规则，非空则 `bookChapter.title = title` 并**写回库**（顺带用 imgRegex 拆出 `reviewImg`）；`runCatching` 吞错。**为什么不算格式欠账直接做**：本仓 `getChapter` 返回纯文本、`ChapterEntry{name,url}` 没有标题位，要接住这条得动门面返回形状 + wire 契约 + 阅读器标题显示（对面那是"改目录条目名"，我们目录是缓存态）——属产品面拍板，不是照抄一行。reviewImg 那半属段评面（`c-review-url` 已判不适用）' },
  { id: 'c-content-sub-content', group: 'C 书源字段', capability: 'ruleContent.subContent（子正文/歌词追加）', status: 'open', note: '本库非空 0 源；「彻底兼容」口径下需实现或判环境不适用（任务 #8 一并拍）' },
  { id: 'c-content-image-decode', group: 'C 书源字段', capability: 'ruleContent.imageDecode / coverDecodeJs（图片二进制解码 JS）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：仅文本源'], note: '漫画/加密图源面；本库 0 源带值，且本插件仅文本源（入库闸已挡）' },
  { id: 'c-content-image-style', group: 'C 书源字段', capability: 'ruleContent.imageStyle（图片排版）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：仅文本源'], note: '排版属阅读器 UI；14 源带值但均为漫画/图片类' },
  { id: 'c-content-source-regex', group: 'C 书源字段', capability: 'ruleContent.sourceRegex（资源 URL 嗅探）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：仅文本源'], note: '音视频直链嗅探，属 WebView 面；本库非空 2 源' },
  { id: 'c-raw-fidelity', group: 'C 书源字段', capability: 'raw 原文保真（供存量重推与方言判别）', status: 'implemented', impl: ['src/services/sources.ts', 'contentTypeOfRaw'], test: ['tests/services/sources.test.ts', 'load 归一：早期数据缺 enabled'] },
  { id: 'c-stringified-rule-objects', group: 'C 书源字段', capability: 'rule 容器可以是「字符串化的 JSON」（对面各 JsonDeserializer）', status: 'implemented', impl: ['src/services/normalize.ts', 'ruleContainer'], test: ['tests/services/normalize.test.ts', '规则容器的字符串化形态'], note: '对面给**每一个** rule 对象都写了 deserializer，两条分支一致：`isJsonObject` 直通、`isJsonPrimitive` 把字符串再 parse 一次（`data/entities/rule/BookInfoRule.kt` 等五份）。此前本仓对非对象容器 continue → 这类源导入后搜索/目录/正文规则整块丢失，表现成「缺规则」像源坏了。现量：本库 **0/158** 用该形态（公开分享里常见，属格式本身不是自造形态）；只接 legado 方言五块，Native 侧不接（对面那条分支在 legado 的 Gson 侧，没有 Native 的规格依据）' },
  { id: 'c-unmapped-silent', group: 'C 书源字段', capability: '未映射顶层字段的处置', status: 'implemented', impl: ['src/services/normalize.ts', '已忽略不支持的子字段'], note: '对象方言子字段会点名；顶层未列字段目前静默落地板（已知弱点）', test: ['tests/services/normalize.test.ts', '聚合 warning'] },

  // ── D 搜索与发现 ────────────────────────────────────────────────────
  { id: 'd-search-face', group: 'D 搜索与发现', capability: '搜索面单点（模板→组装→抓取→列表规则→条目）', status: 'implemented', impl: ['src/services/search-face.ts', 'fetchSearchPage'], test: ['tests/services/search-face.test.ts', '条目提取'] },
  { id: 'd-book-list-fallback', group: 'D 搜索与发现', capability: '书名/作者/URL/封面/简介/最新章节（对面条目字段 lastChapter）/分类/字数 八字段展开 + 空名条目丢弃', status: 'implemented', impl: ['src/services/reading.ts', 'searchOne'], test: ['tests/services/reading.test.ts', 'search 命中并分组'] },
  { id: 'd-book-type-constants', group: 'D 搜索与发现', capability: 'bookType/BookType 位标志体系', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：书籍类型位标志体系'], note: '本仓以 type∈{text,audio,image,file,unknown} 单值 + 入库闸替代；参与集唯一判定 participates' },
  { id: 'd-name-author-cleanup', group: 'D 搜索与发现', capability: '书名/作者规范化（剥「作 者」「著」等前后缀）', status: 'implemented', impl: ['src/services/normalize.ts', 'stripLeadingIcons'], note: '本仓剥名称前缀图标；对面的 nameRegex/formatBookAuthor 语义未全接（残余形态未见真机报告）', test: ['tests/services/normalize.test.ts', '图标剥离'] },
  { id: 'd-search-paging', group: 'D 搜索与发现', capability: '搜索翻页（page 变量入 URL）', status: 'open', note: 'fetchSearchPage 硬编 page:1；**2026-09-22 按 raw 现量 94/214** 源的 searchUrl 带 `{{page}}`（此前各注的 48、59 都是在漂的分母上数的旧值）。补它要的是门面 + UI 的「加载更多」入口（每源只搜一次是产品形状），不是格式缺口 → 待拍板。任务 #6' },
  { id: 'd-empty-list-info-item', group: 'D 搜索与发现', capability: '列表规则零命中（或缺规则）时按详情页解析出一条书目', status: 'implemented', impl: ['src/services/search-face.ts', 'fetchSearchPage'], test: ['tests/services/search-book-url-pattern.test.ts', '列表 0 条 + 无 pattern'], note: '对面守卫是 `bookUrlPattern.isNullOrEmpty()`：声明了嗅探却没命中就是 0 结果，不回落。缺 ruleBookList 也不再是 RuleMissing（`getElements("")` = 空列表）。探针区分 `via`：empty-list 仍按「零命中」换词重试，不当 verified' },
  { id: 'd-precise-search', group: 'D 搜索与发现', capability: '精准搜索（书名+作者相等即早停）', status: 'implemented', impl: ['src/services/reading.ts', 'searchProgressive'], note: '本仓按源并发 + 每源截断 50 条实现同等效果；对面 shouldBreak 是逐源早停', test: ['tests/services/reading.test.ts', 'searchPlan：参与集唯一主人'] },
  { id: 'd-merge-dedup', group: 'D 搜索与发现', capability: '跨源结果合并（equal>tags>contains>other 四桶、按 (name,author) 归并 origins）', status: 'open', note: '本仓按源分组呈现、不做跨源归并排序；属产品呈现决策，非格式欠账' },
  { id: 'd-explore-three-forms', group: 'D 搜索与发现', capability: 'exploreUrl 三形态（@js 产出 JSON / ExploreKind 数组 / `标题::URL` 多行）', status: 'open', note: '见 c-explore-url；对面失败时塞 ERROR 卡片不抛。待拍板后与书城 UI 同批' },
  { id: 'd-explore-fallback-search-rule', group: 'D 搜索与发现', capability: 'ruleExplore.bookList 为空时整体回落 ruleSearch', status: 'open', note: '随发现面一并实现才有意义' },
  { id: 'd-groups-scope', group: 'D 搜索与发现', capability: '按分组/启停限定搜索范围', status: 'implemented', impl: ['src/services/reading.ts', 'searchPlan'], test: ['tests/services/reading.test.ts', '非文本源不参搜'] },
  { id: 'd-check-flow', group: 'D 搜索与发现', capability: '书源校验（搜索/发现/详情/目录/正文 五开关 + 组名打标 js失效/网站失效/校验超时）', status: 'implemented', impl: ['src/services/probe.ts', 'probeSource'], note: '本仓只做搜索面探针（verified/broken/unverified + 待办箱）；多阶段校验由 DSH_CONTENT_AUDIT 承担', test: ['tests/services/probe.test.ts', 'broken 口径'] },
  { id: 'd-respond-time-inflation', group: 'D 搜索与发现', capability: '失败时把 respondTime 人为放大以沉底', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：respondTime 排序轴'], note: '本仓排序按导入序 + 待办箱置顶坏源，无 respondTime 轴（对面该字段亦只影响排序）' },

  // ── E 书籍详情 ──────────────────────────────────────────────────────
  { id: 'e-detail-fields', group: 'E 书籍详情', capability: '详情八字段（书名/作者/封面/简介/最新章节 `lastChapter`/分类/字数/目录地址）', status: 'implemented', impl: ['src/services/reading.ts', 'getDetail'], test: ['tests/api/dispatch-reading.test.ts', 'book'] },
  { id: 'e-aux-field-error-isolation', group: 'E 书籍详情', capability: 'kind / wordCount / lastChapter / intro / coverUrl 五项读取炸掉只丢该字段，不带走书目（对面 try/catch 口径）', status: 'implemented', impl: ['src/services/bridge.ts', 'metaFieldOf'], test: ['tests/services/reading.test.ts', '辅助字段的坏规则只丢该字段'], note: '对面 `model/webBook/BookList.kt`（getSearchItem）与 `model/webBook/BookInfo.kt` 里包 `try { … } catch { Debug.log }` 的**恰是这五项**，裸奔的是 name / author / bookUrl / tocUrl（那四个不在 try 里：空即丢条目、炸即整次失败）。本仓同边界：五个辅助字段经 `metaFieldOf`/`auxFieldOf` 吞异常留空，四个裸奔项维持宁炸不猜。不吞的具体代价：现库有 9 源把 kind/wordCount 写成无终端裸串（普查计到其中 3 源 5 条解析期抛），不吞就把这些源的整组书目打成 error——**接入字段反而造欠账**。钉子两侧都钉：只钉「吞」等于放行「什么都吞」。**一条有意偏差（2026-09-22 复核对面源码后登记）**：空产物**不**折成缺席——`BookList.getSearchItem` 是 `book.wordCount = wordCountFormat(…)` 直接赋值，只有 `BookInfo.analyzeBookInfo` 逐字段 `if (it.isNotEmpty())`；本仓两个面共用 `metaFieldOf`，一律照赋值（空串是空串、不是 Miss——取值规约不许把空值与取位失败折成一种）。代价如实写：详情面已有值遇到空读数会被清成空串（对面保留旧值）；要逐面照抄就得让同一个 helper 按面分叉，属独立改动。' },
  { id: 'e-detail-fallback-flat', group: 'E 书籍详情', capability: 'ruleDetail* 缺失时回退搜索面字段', status: 'implemented', impl: ['src/services/bridge.ts', 'detailFieldsOf'], test: ['tests/services/reading.test.ts', 'ruleDetail'] },
  { id: 'e-init-replace-content', group: 'E 书籍详情', capability: 'init 产物整体替换后续规则的求值上下文与 html', status: 'implemented', impl: ['src/services/bridge.ts', 'detailContextOf'], test: ['tests/services/reading.test.ts', '换根'] },
  { id: 'e-toc-html-reuse', group: 'E 书籍详情', capability: "tocUrl == bookUrl 时复用详情响应体（省一次请求）", status: 'open', note: "对面 model/webBook/BookInfo.kt `if (book.tocUrl == baseUrl)` 直接拿 infoHtml 建目录。本仓实测：`src/services/reading.ts` 的 `fetchText`**不接任何页面级缓存**，getDetail 与 getToc 是两次门面调用，同一条 URL 会真打两次网络——对面在自己的调用里省掉了。这条不是「缓存已覆盖」：PageCache 存的是**目录条目/正文**，不是详情页原文。补法要先定形状（按 (sourceId,url,规则代际)  memo 详情页 body？还是给 fetchText 加页面级缓存并吃代际失效），代价是「详情刷新后仍读到旧 body」这一类新问题，与本仓刚立起来的缓存代际口径相互作用 → 要拍板，不是照抄一行就行" },
  { id: 'e-info-html-reuse', group: 'E 书籍详情', capability: '搜索响应已含详情时跳过详情网络', status: 'open', note: '与 e-toc-html-reuse 同一族（infoHtml）' },
  { id: 'e-word-count-format', group: 'E 书籍详情', capability: 'wordCount 数字化格式化（x字 / x.x万字）', status: 'implemented', impl: ['src/services/bridge.ts', 'formatWordCount'], test: ['tests/services/bridge.test.ts', '整串是整数才转换'], note: '**原判定「不适用：对面亦只在 UI 格式化」是错的**——`wordCountFormat` 在 `model/webBook/BookList.kt` 与 `model/webBook/BookInfo.kt`（解析层）就被调用，存进 book 的已经是格式化后的串。现按对面 `utils/StringUtils.kt` 逐条搬：整串匹配 `-?[0-9]+` 才转换、`>10000` 走 `DecimalFormat("#.#")`（HALF_EVEN 舍入，非四舍五入）、≤0 变空、非数字原样给回。' },
  { id: 'e-intro-special-prefix', group: 'E 书籍详情', capability: "intro 以 <usehtml>/<md>/<useweb> 开头则原样保留不净化（**只有详情面豁免**）", status: 'implemented', impl: ['src/services/content.ts', 'INTRO_DIRECTIVE'], test: ['tests/services/intro-format.test.ts', '详情面）→ trimStart 后原样保留'], note: "对面 model/webBook/BookInfo.kt：先 trimStart 判三种前缀，命中就把**含前缀的原串**交给渲染层（注释写明：否则 <button>@onclick 等书源交互标记会被清理掉）；model/webBook/BookList.kt 的搜索面**不认**前缀，恒净化。本仓按面传 keepDirective，两侧不对称照抄。现库 1 源（米读小说 ruleBookInfo.intro 是整页 CSS + 卡片 HTML）。渲染指令本仓没有对应渲染器（纯文本阅读器），保留前缀的价值在于**不把源码当净化后的正文**，也让后续要渲染时判得出来" },
  { id: 'e-intro-format-html', group: 'E 书籍详情', capability: "简介是展示文本：HtmlFormatter.format 的正则流水线 + take(5000)", status: 'implemented', impl: ['src/services/content.ts', 'formatIntro'], test: ['tests/services/intro-format.test.ts', '块级标签转换行，其余标签连属性一起删'], note: "对面两个取值点共用 format(...).take(5000)：块级标签(div/p/br/hr/hN/article/dd/dl)转换行、注释与其余标签连属性删除、nbsp/ensp/emsp 转空格、thinsp/zwnj/zwj 删除、换行折叠成「换行 + 两个全角空格」。本仓移植在 content.ts 的 formatIntro，两条有意偏差都只动空白：① 串尾再收一次（对面 Java s 不认全角空格，产物以「换行+缩进」收尾，本仓展示/导出契约是不留尾空行）；② 串首缩进统一两个全角空格（对面 format 会把首行补成四个，它自己后来在 formatDisplayText 里以「先清空再统一补」修掉）。Miss 仍是 null，不折成空串" },
  { id: 'e-can-re-read', group: 'E 书籍详情', capability: 'checkKey / canReRead / 重读控制', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：重读与换源校验键'], note: '参考实现侧确认：本 fork 全仓 grep checkKey 无匹配（对面亦不存在该字段）' },

  // ── F 目录 ──────────────────────────────────────────────────────────
  { id: 'f-toc-rules', group: 'F 目录', capability: 'chapterList/chapterName/chapterUrl 三规则 + 列表规则回退 ruleBookList', status: 'implemented', impl: ['src/services/reading.ts', 'getTocInner'], test: ['tests/services/reading.test.ts', '缺目录/正文规则 → RuleMissingError'], note: '三规则缺一即抛不是本仓自设门槛：对面 `BookChapterList` 只在 `bookChapter.title.isNotEmpty()` 时才收该章，chapterName 缺失 → 全章标题为空 → 目录同样为空；url 缺失则逐章回退 baseUrl（本仓 `f-toc-url-fallback` 同口径）。差别只在对面静默空、本仓点名缺哪条规则（审计实证 5 源落在此型）' },
  { id: 'f-toc-url-per-item', group: 'F 目录', capability: '章 URL 不即时绝对化、延迟拼接并保留选项', status: 'implemented', impl: ['src/services/reading.ts', 'absUrlKeepOption'], test: ['tests/services/url-option.test.ts', 'absUrlKeepOption'] },
  { id: 'f-toc-url-fallback', group: 'F 目录', capability: '章 URL 为空逐章回退目录页（对面另有「卷名用标题替代」）', status: 'implemented', impl: ['src/services/reading.ts', 'extract'], note: '整本每条都回退 → 抛错点名 ruleChapterUrl（本仓比对面严：全回退即规则失效）', test: ['tests/services/reading.test.ts', '仍逐章回退目录页'] },
  { id: 'f-toc-paging', group: 'F 目录', capability: 'nextTocUrl 翻页（单候选串行、多候选并发不递归、防环）', status: 'implemented', impl: ['src/services/pagination.ts', 'followPages'], test: ['tests/services/pagination.test.ts', '正常跟完 3 页'] },
  { id: 'f-toc-reverse-twice', group: 'F 目录', capability: '目录两次 reverse（配合 getReverseToc）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：目录整本倒序轴'], note: '本仓无「整本倒序阅读」开关，链首 `-` 前缀已覆盖倒序需求' },
  { id: 'f-toc-cache', group: 'F 目录', capability: '目录缓存 + 规则变更失效 + 并发去重', status: 'implemented', impl: ['src/services/cache-epoch.ts', 'rulesEpoch'], test: ['tests/services/cache-epoch.test.ts', '逐字段翻转'] },
  { id: 'f-toc-empty-exception', group: 'F 目录', capability: '空目录异常分类（TocEmptyException 等价）', status: 'implemented', impl: ['src/services/reading.ts', '目录 URL 规则未取到任何章节地址'], test: ['tests/services/reading.test.ts', '缺目录/正文规则 → RuleMissingError'] },
  { id: 'f-txt-toc-rule', group: 'F 目录', capability: 'TxtTocRule 可配置正则集（chapterRule/volumeRule/打分选规则）', status: 'open', note: '本仓本地 TXT 是一条钉死 CHAPTER_RE；对面按内容打分挑规则。属功能补全（无对应用户可配面）。任务：待 #8 拍板' },
  { id: 'f-chapter-tag-update-time', group: 'F 目录', capability: '章节 tag（更新时间/附加信息）与 isVolume 层级', status: 'open', note: '同 c-toc-flags：ChapterEntry 形状要扩，牵 wire 契约' },

  // ── G 正文 ──────────────────────────────────────────────────────────
  { id: 'g-content-rule', group: 'G 正文', capability: 'ruleContent 取值（usage=value）+ 空产出绝不静默', status: 'implemented', impl: ['src/services/reading.ts', 'getChapter'], test: ['tests/services/reading.test.ts', '正文规则'] },
  { id: 'g-next-content', group: 'G 正文', capability: 'nextContentUrl 多页串接（串行/并发不递归、页间插行）', status: 'implemented', impl: ['src/services/pagination.ts', 'followPages'], test: ['tests/services/pagination.test.ts', '串章'] },
  { id: 'g-chapter-boundary-guard', group: 'G 正文', capability: '「下一页==下一章 URL 即停」的目录知识闸', status: 'implemented', impl: ['src/services/pagination.ts', 'stopUrls'], test: ['tests/services/pagination.test.ts', '目录知识'] },
  { id: 'g-html-to-text', group: 'G 正文', capability: 'HTML→纯文本净化（块级换行、script/style 丢弃、img 保留为地址行、noscript 下钻）', status: 'implemented', impl: ['src/services/content.ts', 'contentToText'], test: ['tests/services/content.test.ts', 'noscript'] },
  { id: 'g-entity-decode', group: 'G 正文', capability: '实体解码（数字实体 + 命名白名单，未知原样）', status: 'implemented', impl: ['src/services/content.ts', 'decodeBasicEntities'], test: ['tests/services/content.test.ts', '预转义'] },
  { id: 'g-content-empty-exception', group: 'G 正文', capability: '空正文异常（ContentEmptyException 等价）+ 不写缓存', status: 'implemented', impl: ['src/services/reading.ts', '正文规则没取到内容'], test: ['tests/services/reading.test.ts', '不写缓存'] },
  { id: 'g-unescape-html4', group: 'G 正文', capability: 'getString 默认 unescapeHtml4（正文路径显式关闭）', status: 'implemented', impl: ['src/services/content.ts', 'decodeBasicEntities'], note: '本仓在收口层做白名单实体解码，对面在取值层做 unescapeHtml4——口径等价、未知实体都不猜', test: ['tests/services/content.test.ts', '未知实体'] },
  { id: 'g-paragraph-title', group: 'G 正文', capability: 'paragraphTitle / reSegment 重新分段 / 段首缩进', status: 'open', note: '本仓 normalizeChapterText 做逐行 trim + 空行折叠；对面重分段是排版轴。属 UI 决策' },
  { id: 'g-image-url-options', group: 'G 正文', capability: 'img 地址保留 `,{option}`（图片请求可带 headers）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：仅文本源'], note: '本仓正文把 img 降级为地址行，不发起图片请求' },
  { id: 'g-content-shortcut-empty-rule', group: 'G 正文', capability: '正文规则为空 → 把章节 URL 当正文（对面短路语义）', status: 'implemented', impl: ['src/services/errors.ts', 'RuleMissingError'], note: '本仓判 RuleMissing 而不是拿 URL 冒充正文（宁炸不猜）', test: ['tests/services/reading.test.ts', '点名 facet 与规则名'] },
  { id: 'g-cache-slot-chapter-name', group: 'G 正文', capability: '正文缓存槽位含章名（防章序位移串配）', status: 'implemented', impl: ['src/services/cache-epoch.ts', 'contentSlot'], test: ['tests/services/reading.test.ts', '不串配'] },
  { id: 'g-pay-action', group: 'G 正文', capability: 'ruleContent.payAction（付费动作 JS / 开浏览器）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：仅文本源'], note: '返回值驱动 App 行为；本仓无对应交互面。对面亦只在漫画读源用' },
  { id: 'g-callback-js', group: 'G 正文', capability: 'ruleContent.callBackJs（正文取值后回调脚本）', status: 'open', note: '对面 ContentRule 有此字段；本仓导入时**点名提示不支持**（`tests/services/normalize.test.ts` 的「ruleContent.callBackJs」断言），不静默丢。2026-09-22 按 raw 现量为 0 源，故排在队尾；字段门（`upstream-fields.test.ts`）已把它记成在册欠账，将来出现该形态的源不必重新发现' },
  { id: 'g-review-img-from-title', group: 'G 正文', capability: 'title 命中 img 正则 → 段落评论图标', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：评论与段评面'], note: '随 ruleReview 一并属评论面（对面 ruleReview 本就 dead）' },

  // ── H JS 宿主面 ─────────────────────────────────────────────────────
  { id: 'h-sandbox-escape-defense', group: 'H JS 宿主面', capability: '沙箱逃逸防御（vm realm + codeGeneration 关闭 + 宿主入口锁死）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'codeGeneration'], test: ['tests/engine/js-sandbox.test.ts', '沙箱逃逸：代码生成被禁'] },
  { id: 'h-timeout-double-gate', group: 'H JS 宿主面', capability: '超时双闸（同步 vm timeout + 异步 Promise.race）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'DEFAULT_JS_TIMEOUT_MS'], test: ['tests/services/reading.test.ts', '脚本超时'] },
  { id: 'h-java-post', group: 'H JS 宿主面', capability: 'java.post(url, body, headers) → Jsoup Connection.Response 形态', status: 'implemented', impl: ['src/engine/js-protocol.ts', "method('post'"], test: ['tests/engine/js-sandbox.test.ts', '对面 Jsoup Response 的**方法壳**'], note: '对面 `help/JsExtensions.kt:post` 返回**对象**，脚本写 `res.body()` / `res.cookies()`——不是字符串，故与 ajax 不同：宿主桥只走 JSON 数据面，方法壳在 BOOTSTRAP 内包（函数不跨 worker）。第三参两种形态都收（脚本内联 JS 对象 = 独立合集里的真形态；JSON 串 = Rhino 侧 Gson 转的等价写法），认不出的串点名而不是当没看见。**发现渠道**：本库 214 源零使用，是解析面普查换分母（两份独立公开合集 67 源）才冒出来的，现量 9 源 10 处' },
  { id: 'h-java-t2s', group: 'H JS 宿主面', capability: 'java.t2s / s2t 繁简转换', status: 'open', note: '对面 `utils/ChineseUtils.kt` 转调第三方 `com.github.liuyueyi.quick-transfer` 的词典，**且**在 t2s 前跑自家 `fixT2sDict()` 补丁——所以换一个繁简轮子（opencc 一类）得到的文本与对面**不逐字相等**。独立合集现量 2 源 33 处（多用于书名/章节名繁转简）。要么接受近似并记下差多少，要么搬对面词典（数据文件），需要拍板；未接前照旧点名抛错，不静默返回原文' },
  { id: 'h-java-cache-file', group: 'H JS 宿主面', capability: 'java.cacheFile(url) → 本地文件路径', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：真实文件与压缩包 API'], note: '裁决已在：给脚本真实文件路径 = 数据外泄面。独立合集现量 3 源 5 处（拿它缓存图片密钥再读字节），本仓这条道走 `downloadFile` → 不透明令牌 → 字节/文本读口。此行的意义是**普查换分母后确认该裁决真的有需求方**，不是纸面推演' },
  { id: 'h-java-tourl', group: 'H JS 宿主面', capability: 'java.toURL(str) → java.net.URL 对象', status: 'open', note: '独立合集现量 1 源 1 处。对面返回 JVM URL 对象（脚本再取 `.toString()` / `.openConnection()`），本仓抛「需要安卓宿主环境」。要么给一个只带字符串语义的近似壳（`.toString()` 够用）、要么维持抛错——先看清那 1 源到底调了哪些成员再定，不凭空造壳' },
  { id: 'h-java-ajax-sync', group: 'H JS 宿主面', capability: 'java.ajax 同步语义（对面 runBlocking）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'SYNC_WORKER_RE'], test: ['tests/engine/js-bindings.test.ts', 'java.ajax 同步语义'] },
  { id: 'h-java-ajax-arg-coercion', group: 'H JS 宿主面', capability: 'java.ajax 的实参规约（Rhino 的 String 形参强制转换）', status: 'implemented', impl: ['src/engine/js-protocol.ts', "'ajax'"], test: ['tests/engine/js-bindings.test.ts', 'java.ajax 参数规约'], note: '脚本把上一段的值直接递给 ajax 时，对面按 String(值) 转（JSONPath 的单元素数组 → 那条 URL 本身）；本仓此前把原值交给请求组装层 → `template.replace is not a function`（灯读文学 detail init 段实证）。null/undefined 不猜成 "null" 去打站点，点名参数缺失' },
  { id: 'h-js-protocol-table', group: 'H JS 宿主面', capability: '宿主方法单表登记（JAVA_PROTOCOL → 挂载/分派/类型派生）', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'JAVA_PROTOCOL'], test: ['tests/engine/js-protocol.test.ts', '表 ↔ SANDBOX_MOUNTS 完备'] },
  { id: 'h-get-string-recursive', group: 'H JS 宿主面', capability: 'java.getString/getStringList/getElements/getElement/setContent 递归求值', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'getString'], test: ['tests/engine/evaluate-sync-loop.test.ts', '真实环路'] },
  { id: 'h-get-string-is-url', group: 'H JS 宿主面', capability: 'java.getString(rule, isUrl=true)（取 URL 后再抓 + 绝对化）', status: 'open', note: '现抛 UnsupportedRuleError；本机库 0 源使用。彻底兼容口径下应实现（engineFetch 已具备条件）——随 #8 拍板' },
  { id: 'h-java-open-url', group: 'H JS 宿主面', capability: 'java.openUrl（打开浏览器，脚本侧副作用）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：Android 与 App 宿主能力'], note: '裁决早写明纯 UI 副作用走 no-op，但**挂载时只挂了 open 没挂 openUrl** → 脚本调 openUrl 直接 TypeError，整段 js 失败。2026-09-22 解析面普查（tests/engine/parse-census.test.ts）现量 2 源在调；修法是补一个同款 no-op 挂载，不是改裁决' },
  { id: 'h-java-connect', group: 'H JS 宿主面', capability: 'java.connect（同步 HTTP，对面返回 StrResponse 对象）', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'java.connect'], test: ['tests/engine/js-sandbox.test.ts', 'java.connect(url) →'], note: '与 ajax 同款 worker 同步桥（BOOTSTRAP 手工挂载，mode:async 不进 javaSync 名单）。两点刻意分歧：① 对面第二/三参收 header JSON 与 callTimeout，本仓 ctx.fetch 无请求头通道（头由请求组装层按源规则装配）→ 传了非空 header **点名抛错**，不静默丢脚本意图；② 对面 runCatching 把异常塞进 body（StrResponse(url, stackTraceStr)），本仓失败照旧抛——错误文本冒充正文是最高罪。2 源在调（解析面普查第 22 批抓到，此前是桥缺口）' },
  { id: 'h-java-webview-ua', group: 'H JS 宿主面', capability: 'java.getWebViewUA（取 WebView 的 UA 串）', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'java.getWebViewUA'], test: ['tests/engine/js-sandbox.test.ts', 'java.getWebViewUA：取 ctx.userAgent'], note: '对面返回真 WebView 缓存的 UA；本仓无 WebView，返回**自己实际发出去的那条 UA**（`ctx.userAgent` 与 fetch 同源，含源级覆盖）——对拼 headers 的脚本可用，但它不是设备真实 WebView UA，属**近似**，实现处与本行都点名了这条差。`ctx.userAgent` 未接线 → 点名抛「取不到出站 UA」，绝不编一个串冒充。1 源在调（解析面普查第 22 批抓到，此前是桥缺口）' },
  { id: 'h-java-android-id', group: 'H JS 宿主面', capability: 'java.androidId（设备唯一 ID）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：Android 与 App 宿主能力'], note: '对面取 Settings.Secure.ANDROID_ID。本仓无设备身份：造一个随机值会让脚本拿它做签名/密钥参数，产出**与对面不同但看着合法**的结果，比抛错更坏 → 现挂在 `js-sandbox` 的宿主桩名单里，点名抛「需要安卓宿主环境」（此前是 `java.androidId is not a function`，脚本读不出"这是裁决"）。1 源在调' },
  { id: 'h-abs-urls', group: 'H JS 宿主面', capability: '取值出口 isUrl=true 的绝对化（空结果回落 baseUrl）', status: 'implemented', impl: ['src/services/reading.ts', 'tocUrlOf'], test: ['tests/services/reading.test.ts', 'tocUrl'] },
  { id: 'h-elem-bridge', group: 'H JS 宿主面', capability: '元素集包装：集合面 size/get/eq/each/first/last/toArray + 元素面 text/attr/html/select + org.jsoup.Jsoup.parse', status: 'implemented', impl: ['src/engine/js-sandbox.ts', "case 'split'"], test: ['tests/engine/js-sandbox.test.ts', 'nodes 结果的元素集表面'], note: '本行此前**过度申报**：写的是 size/toArray/first 已实现，实测 size() 恒 1、get/eq/each 根本不存在（钉子指在 Packages 上，没钉住这组 API——矩阵只能验证据存在，验不了覆盖度）。2026-09 由真源 toc 模板逼出真口径：对面 getElements 路径的 result 是 org.jsoup.Elements（集合），size 按顶层元素数算；且**列表用途下前段零命中仍是空集合**（对面空 Elements 照样有方法），否则「站点没这结构」会被误记成引擎侧失败。缺 `.remove()`（改活文档树，另立开口）' },
  { id: 'h-packages-crypto', group: 'H JS 宿主面', capability: 'Packages.java.io / javax.crypto Cipher+Mac / BitmapFactory PNG 解码', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'base64DecodeToByteArray'], test: ['tests/engine/legado-gaps.test.ts', 'AES'] },
  { id: 'h-digest-hmac-family', group: 'H JS 宿主面', capability: 'java.digestHex / digestBase64Str / HMacHex / HMacBase64（摘要与 HMAC 族，JCA 算法名）', status: 'implemented', impl: ['src/engine/js-utils.ts', 'jcaHashName'], test: ['tests/engine/js-protocol.test.ts', '摘要与 HMAC 族'], note: '对面 `help/JsEncodeUtils.kt`：`digestHex(data, algorithm)`——**data 在前、算法在后**，`data.toByteArray()` 是 UTF-8；`HMacHex/HMacBase64` 是**大写 H 开头**的原样方法名（对面靠 @Suppress("FunctionName") 保住这个畸形名，改名等于把 API 弄没）。算法名走 JCA（`SHA-256`/`HmacSHA512`），node 要的是 `sha256`/`sha512` → 显式映射表 + 认不出即点名（对面是 NoSuchAlgorithmException，本桥不静默退成 md5）。期望值全部由 **openssl 3.5.6 独立算出**（不是 node crypto，那等于拿实现自证），其中 HMAC-SHA256/20×0x0b 那条同时是 RFC 4231 test case 2 的公开值。**做过≠够不着**：这四个名字曾同时出现在协议表（真实现）与 `js-sandbox` 的「需要安卓宿主」桩名单里，而后挂的桩覆盖了真实现——协议表测试全绿、脚本一调就抛。2026-09-22 由解析面普查的面 C（桥可达性对账）抓出并从桩名单摘掉；回归钉子是 `tests/engine/js-sandbox.test.ts` 的「摘要 / HMAC 族**经沙箱可达**」' },
  { id: 'h-jsoup-live-node-navigation', group: 'H JS 宿主面', capability: 'jsoup 节点导航：Element.parent()/children()/elementSiblingIndex()/nextElementSibling() 等（result 是**活节点**）', status: 'open', note: '**架构级差异，不是缺一个方法**：对面的条目元素是解析后页面树里的活节点，`result.parent()` 返回条目在页面里的真实父节点；本仓条目是**脱离文档的 outerHTML 片段**（`reading.searchOne`/`getTocInner` 逐条 ctx），片段的父与兄弟在数据里根本不存在。2026-09-22 按 raw 现量 **0/214**（旧读数的实证源「金银小说网」已被用户删出库，架构级判断不依赖它成立） `coverUrl: "@js:(function(){…var p=result.parent();var i=result.elementSiblingIndex();var img=p.children().get(i-1).select(\'img\').first();…"`（取前一个兄弟里的图当封面），且脚本包在 `try{}` 里 → 今天表现为**封面静默为空**而不是报错。要接得先把条目改成携带 (文档, 选择器) 的形状——牵动条目提取/缓存/去重三处，属独立工程，不是照 js-sandbox 的 remove() 那样再补一个桥方法' },
  { id: 'h-aes-shim', group: 'H JS 宿主面', capability: 'java.aesBase64DecodeToString / createSymmetricCrypto().decryptStr', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'aesBase64DecodeToString'], test: ['tests/engine/js-sandbox.test.ts', 'AES'] },
  { id: 'h-encrypt-side', group: 'H JS 宿主面', capability: '加密侧：aesEncode*/desEncode*/tripleDES*/RC4/HMac 已接，剩 createAsymmetricCrypto().getSignature().sign* 与非对称加密', status: 'open', doc: ['docs/design/legado-compat.md', '不适用：加密/签名的加密侧'], note: '**2026-09-22 现量 0/158**（全库 java.* 普查：加密方向一个没有——用的全是 `md5Encode`×6、`base64Decode`×7、`aesBase64DecodeToString`×3、`createSymmetricCrypto(...).decryptStr`×3，即摘要与解密方向）。摘要/HMAC 族本轮已接（矩阵 `h-digest-hmac-family`）。**剩下的非对称族刻意不做**：它的正确性取决于安卓 KeyStore 的 key 规格解释（PKCS#8 vs PKCS#1 DER、`RSAPublicKey` 装配、`SHA256withECDSA` 签名编码），自造密钥对自签自验的测试**证明不了与对面一致**——做错比不做更糟。加签类源出现时按那条源补（沙箱拒绝名单会给出口径）' },
  { id: 'h-font-anti-scrape', group: 'H JS 宿主面', capability: 'queryTTF/queryBase64TTF/replaceFont（字体反混淆）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：字体反混淆'], note: '本库 0 源使用；对面依赖 App 字体渲染栈' },
  { id: 'h-tts-and-search-bridges', group: 'H JS 宿主面', capability: 'java.searchBook / startBrowserAwait / getVerificationCode / webViewGetSource', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：Android 与 App 宿主能力'], note: '属 App 交互/验证码识别/朗读面；toast/startBrowser/openUrl 走明确 no-op' },
  { id: 'h-to-num-chapter', group: 'H JS 宿主面', capability: 'java.toNumChapter（中文数字 ↔ 章节序号）', status: 'implemented', impl: ['src/engine/js-utils.ts', 'toNumChapter'], test: ['tests/engine/js-utils.test.ts', '第X章 的中文数字转阿拉伯数字'], note: '5+ 源在正文/目录的 @js 里调它规整 `第…章`；对面只回「第+数字+章」（标题尾部丢弃）——照抄对面，不自写更聪明的版本' },
  { id: 'h-source-refresh-explore', group: 'H JS 宿主面', capability: 'source.refreshExplore() / refreshJSLib()', status: 'open', note: '复核修正（本会话早前记为「9 源在调，是独立欠账」）：本机 158 源里 refreshExplore 的 9 处出现**全部**在 exploreUrl 的 action 串里（发现页「换一换」按钮），非发现面链路零需求 → 随发现面一并落地' },
  { id: 'h-cache-shim', group: 'H JS 宿主面', capability: 'cache put/get/delete(+Memory 三别名)', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'cachePutMemory'], test: ['tests/engine/content-facet.test.ts', 'cache 垫片'] },
  { id: 'h-cache-ttl', group: 'H JS 宿主面', capability: 'cache 带 TTL 与磁盘层级', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：缓存 TTL 与磁盘层级'], note: '本仓 CacheManager 等价物只有进程内键值表（按源隔离）' },
  { id: 'h-file-store', group: 'H JS 宿主面', capability: 'java.downloadFile / readTxtFile', status: 'implemented', impl: ['src/engine/js-protocol.ts', 'downloadFile'], test: ['tests/engine/legado-gaps.test.ts', 'downloadFile'] },
  { id: 'h-file-extra-apis', group: 'H JS 宿主面', capability: 'unzipFile/getZipString/getTxtInFolder/importScript/cacheFile 路径式文件族', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：真实文件与压缩包 API'], note: '脚本可读任意本地路径=数据外泄面；本仓只给不透明令牌暂存表' },
  { id: 'h-source-variable', group: 'H JS 宿主面', capability: 'source.getVariable/setVariable/put/get + getKey/header', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'SourceSession'], test: ['tests/engine/source-session.test.ts', '源变量同样按 session/源建档'] },
  { id: 'h-elems-remove', group: 'H JS 宿主面', capability: 'Elements.remove() 就地删节点（result.select("p,script,div").remove() 后 result.html() 已不含它们）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', "case 'remove'"], test: ['tests/engine/js-sandbox.test.ts', '元素桥 remove()'], note: '元素桥的片段从「构造时常量」改成住在 box 里：select() 把 owner={box,rule} 交给集合，remove() 让宿主摘完节点回写 box.html，产出它的那个元素此后每个读法（html/text/select/String）都看见净化后的树。对面是活 jsoup 文档，且 `Element.remove()` 只把节点从**父**上摘走、子树跟着节点走——顶层元素自己被摘掉之后仍要读到幸存的 em，故宿主在摘前先按原形状记下顶层节点。集合级 select / toArray / java.getElements 产出的集合背后没有可回写的片段，remove() 如实抛，不静默 no-op（静默等于把脏节点当已净化交给正文）。真机实证 2 源：环安小说网（content-error，本次修掉）、悦读小说（ruleContent 同形态，但它卡在 toc 的 URL 选项后缀）。**更正本行旧注**：原文写「该脚本另有 eval() 一条安全边界在等着」是错的——两条 ruleContent 逐字核过 sources.json，都没有 eval / new Function' },
  { id: 'h-list-context-collection', group: 'H JS 宿主面', capability: '列表路径（对面 getElements）的 result 绑成**元素集合**：forEach/length/下标 + size/get/eq/first/last/each/toArray', status: 'implemented', impl: ['src/engine/js-sandbox.ts', "d.resultCtx === 'list'"], test: ['tests/engine/js-sandbox.test.ts', '列表上下文的 result 是元素集'], note: '对面 result 是 java List/Elements，脚本 `result.forEach(e=>…)`（西瓜书屋 ruleChapterList）、`r.length-v`（穿越小说）全靠集合形态；取值路径（getString）仍是字符串对象，两条路的身份用 JsHost.resultCtx（= ParsedRule.usage）分派，不设第三份判定表' },
  { id: 'h-book-entity-methods', group: 'H JS 宿主面', capability: 'book/chapter 实体方法面：getType/setType、getVariable/putVariable/removeVariable、getName/getBookUrl/getOrigin', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'mkHostObj'], test: ['tests/engine/js-sandbox.test.ts', 'book.setType/getType 与 getVariable/putVariable'], note: '真机实证：终极全栖 `book.setType(4)`、穿越小说 `book.getVariable("custom")`。**Book 变量表与 source 变量表分开**（对面 Book.variables 与 BookSource.variables 是两个存储，钉子钉住不串味）；本仓无 Book 级持久存储，变量只活一次规则调用——对面是跨启动持久，差异登记在 a-var-scope-chain 一族' },
  { id: 'h-packages-org-jsoup', group: 'H JS 宿主面', capability: 'Packages.org.jsoup.Jsoup.parse 与 org.jsoup.Jsoup.parse 同源（对面 Rhino 两种包路径写法）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'org: { jsoup'], test: ['tests/engine/js-sandbox.test.ts', 'Packages.org.jsoup.Jsoup.parse'], note: '金银小说网 ruleContent 用 Packages. 前缀写法，此前撞 `Cannot read properties of undefined (reading jsoup)`' },
  { id: 'h-elems-enumerability', group: 'H JS 宿主面', capability: '元素集合的 for-in 只遍历成员（Rhino Java 数组语义）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'enumerable: false'], test: ['tests/engine/js-sandbox.test.ts', 'each() 遍历成员'], note: '真源 toc 模板 for(i in list){ l[s[i]] = list[i] } 依赖此；助手若可枚举会把 toArray/size 当元素遍历，当场炸 .text is not a function' },
  { id: 'h-js-lib-eval', group: 'H JS 宿主面', capability: 'jsLib 里用 eval/new Function 的源（对面 Rhino 允许）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：jsLib 里的字符串代码生成'], note: '沙箱逃逸防御的硬边界，明确不支持而非降级（实测 6 源含此形态）' },
  { id: 'h-result-binding', group: 'H JS 宿主面', capability: 'result 三态绑定（JSON 对象 / 元素包装 / 原文）+ JSON.parse 幂等 wrap', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'BOOTSTRAP'], test: ['tests/engine/json-parse-object-idempotent.test.ts', '幂等'] },
  { id: 'h-cookie-shim', group: 'H JS 宿主面', capability: 'cookie.getCookie/setCookie/removeCookie（对面域匹配 + Set-Cookie 联动）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'SourceSession'], note: '本仓只做到按源隔离的键值表；见 b-cookie-jar 的开口', test: ['tests/engine/js-sandbox.test.ts', 'cookie'] },
  { id: 'h-android-packages', group: 'H JS 宿主面', capability: 'android.* / org.* 非 jsoup 部分 / java.lang.Thread 等', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：Android 与 App 宿主能力'], note: '一律如实报「需要安卓宿主环境」，不静默 no-op' },
  { id: 'h-rhino-vs-vm', group: 'H JS 宿主面', capability: 'Rhino 引擎语义（sloppy 作用域、Java 互操作、无硬超时）', status: 'implemented', impl: ['src/engine/js-sandbox.ts', 'runAsScript'], note: '本仓 Node vm + 垫片承接主导形态；对面 Rhino 特有语义（如 Java.extend）不接', test: ['tests/engine/js-bindings.test.ts', '非严格模式'] },

  // ── I App 级规则族 ──────────────────────────────────────────────────
  { id: 'i-global-replace-rule', group: 'I App 级规则族', capability: 'ReplaceRule 全局替换库（scope/excludeScope/isRegex/@js 替换体/超时看门狗）', status: 'open', note: '本仓净化只有规则串内的 `##` 尾与源内 replaceRules[]（导入期固化）。全局替换属 App 级配置 + UI，跨源生效——待拍板' },
  { id: 'i-dict-rule', group: 'I App 级规则族', capability: 'DictRule 字典取词/纠错替换', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：字典取词与纠错（DictRule）'], note: '属阅读器附加功能（取词翻译），不影响书源可读性；本库无对应诉求' },
  { id: 'i-highlight-rule', group: 'I App 级规则族', capability: 'HighlightRule / BookMarking 划线高亮', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：划线高亮与书签（阅读器 UI 面）'], note: '阅读器 UI 面（对面 fork 新增），不属书源格式' },
  { id: 'i-rule-sub', group: 'I App 级规则族', capability: 'RuleSub 书源在线订阅 + sourceUrls 订阅清单导入', status: 'open', note: '本仓导入只收 .json 文件/粘贴文本；对面 JSON 对象含 sourceUrls 会逐个 URL 拉取递归解析。低成本可补，待拍板（涉及自动网络拉取）' },
  { id: 'i-txt-toc-rule', group: 'I App 级规则族', capability: 'TxtTocRule 集（对面独立实体 + 导入对话框）', status: 'open', note: '见 f-txt-toc-rule' },
  { id: 'i-rule-complete', group: 'I App 级规则族', capability: 'RuleComplete 编辑器规则补全', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：编辑器侧规则补全'], note: '编辑器侧便利功能，无运行期语义' },

  // ── J 评论与源类型 ──────────────────────────────────────────────────
  { id: 'j-review', group: 'J 评论与源类型', capability: 'ReviewRule 段评面', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：评论与段评面'], note: '参考实现侧 ruleReview 不落库、无读取点（dead）；本库 0 源带值' },
  { id: 'j-rss', group: 'J 评论与源类型', capability: 'RssSource 订阅源（同一套规则引擎的第二个源类型）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：RSS 订阅源面'], note: '本插件定位是小说（legado 书源），RSS 是另一种源实体与另一套 UI' },
  { id: 'j-audio-image-file', group: 'J 评论与源类型', capability: '音频/图片/文件源完整链路（含下载、朗读、漫画阅读器）', status: 'not-applicable', doc: ['docs/design/legado-compat.md', '不适用：仅文本源'], note: '入库闸拒 + participates 双挡，留库不删；2026-09-22 按规范化 `type` 现量 40/214 源属此类' },
  { id: 'j-local-book', group: 'J 评论与源类型', capability: '本地书（TXT 导入；对面另有 epub/mobi/umd/pdf）', status: 'implemented', impl: ['src/services/localbooks.ts', 'splitChapters'], note: '本仓只做 TXT（解码 + 偏移切片）；其余格式属新增能力，无对应诉求', test: ['tests/services/localbooks.test.ts', 'GBK 回退'] },

  // ── K 书源管理与调试 ────────────────────────────────────────────────
  { id: 'k-import-dedup', group: 'K 书源管理与调试', capability: '导入去重（对面按 lastUpdateTime 判 New/Update/Existing + importKeep* 开关）', status: 'implemented', impl: ['src/services/intake.ts', 'SourceIntake'], note: '本仓按址去重 + 「可用者为准」；对面还比字段级差异并保留本地名称/分组/启停', test: ['tests/services/intake.test.ts', '已有 verified 同址'] },
  { id: 'k-import-formats', group: 'K 书源管理与调试', capability: '导入形态（数组 / 单对象 / sourceUrls 订阅清单 / 绝对 URL 输入 / 字符串化 rule 容器）', status: 'open', note: '本仓只认 JSON 数组或单对象（文件与粘贴）；URL 输入与订阅清单见 i-rule-sub' },
  { id: 'k-export-sources', group: 'K 书源管理与调试', capability: '书源导出回 legado JSON（全量/选中）', status: 'open', note: '本仓只进不出（raw 在场但无序列化口）。备份/迁移的实用缺口，成本低' },
  { id: 'k-edit-source', group: 'K 书源管理与调试', capability: '编辑单源规则/字段', status: 'open', note: '无 PUT sources/:id；对面有完整规则编辑器。要不要给、给到什么形态属产品拍板' },
  { id: 'k-debug-page', group: 'K 书源管理与调试', capability: '书源调试（model/Debug.kt：`标题::URL`/`++URL`/`--URL`/绝对 URL/关键词 + 阶段事件流 + 响应回显）', status: 'open', note: '本仓 evaluateWithTrace 零生产消费者；只有失败时的段号。对「为什么这本读不出」的排障收益最大' },
  { id: 'k-probe', group: 'K 书源管理与调试', capability: '单源探针 + 批量验证（并发限流）', status: 'implemented', impl: ['src/services/probe.ts', 'probeSource'], test: ['tests/services/import-job.test.ts', '批量验证'] },
  { id: 'k-groups-sort-filter', group: 'K 书源管理与调试', capability: '分组、排序（customOrder/名称/响应…）、过滤器（enabled/group:/need_login…）', status: 'implemented', impl: ['src/client/source-list-view.ts', 'stats'], note: '本仓过滤面为文本/状态/分组三类；对面 customOrder 排序键未接（零命中，按导入序）', test: ['tests/client/source-list-view.test.ts', '过滤'] },
  { id: 'k-source-variables-cleanup', group: 'K 书源管理与调试', capability: '删源时连带清 cookie 与源变量', status: 'implemented', impl: ['src/services/reading.ts', 'removeSource'], test: ['tests/services/reading.test.ts', 'removeSource / removeSources：单删与批删'] },
  { id: 'k-auth-redline', group: 'K 书源管理与调试', capability: '登录态（对面 AES 加密落库，key 来自 androidId）', status: 'implemented', impl: ['src/services/sources.ts', 'toPublic'], note: '本仓 auth 只落本机文件、投影层剥除；不做加密（DSH 数据根本身在本机）', test: ['tests/services/sources.test.ts', 'toPublic 不含 raw/rules/auth'] },
  { id: 'k-tools-face', group: 'K 书源管理与调试', capability: 'agent 工具面六件套（搜索/读/目录/书架/源管理/导入）', status: 'implemented', impl: ['src/tools/tools.ts', 'buildTools'], test: ['tests/tools/tools.test.ts', 'dshnovel_'] },
  { id: 'k-content-audit-gate', group: 'K 书源管理与调试', capability: '真机全链路审计与逐源分桶', status: 'implemented', impl: ['tests/content-audit.test.ts', '正文审计'], test: ['tests/content-audit.test.ts', 'sources.json 全量'] },
]
